<?php
require_once __DIR__.'/config/config.php';
$lastUpdated=db()->query('SELECT MAX(updated_at) FROM stories')->fetchColumn();
$categories=db()->query('SELECT name FROM categories ORDER BY name')->fetchAll(PDO::FETCH_COLUMN);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>About Us - Nepal Disaster Archive</title>
<style>body{margin:0;background:#f7f3ed;color:#17202a;font-family:Georgia,serif}.nav{position:sticky;top:0;background:#111820;color:#fff;z-index:10;padding:15px 5%;display:flex;align-items:center;gap:25px;font-family:Arial}.nav a{color:#fff;text-decoration:none;font-size:13px}.logo{font-weight:900;letter-spacing:2px}.navlinks{margin-left:auto;display:flex;gap:18px}.page{max-width:1050px;margin:70px auto;padding:0 25px}.eyebrow{color:#9e2b25;font:800 13px Arial;text-transform:uppercase;letter-spacing:1px}.page h1{font-size:clamp(44px,7vw,76px);line-height:1;margin:15px 0 25px}.lead{font-size:21px;line-height:1.7;color:#555;max-width:800px}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:22px;margin-top:45px}.block{background:#fff;border:1px solid #d9d0c6;border-radius:8px;padding:25px}.block h2{margin-top:0;font-size:25px}.block p,.block li{line-height:1.7;color:#555}.block ul{padding-left:22px}.back{display:inline-block;margin-top:35px;color:#9e2b25;font:700 14px Arial;text-decoration:none}.footer{background:#111820;color:#d8dde0;padding:45px 7%;font-family:Arial;margin-top:70px}.footer strong{color:#fff;letter-spacing:1px}.footer p{line-height:1.6}.social-links{display:flex;gap:14px;margin-top:20px}.social-links a{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border:1px solid #59636a;border-radius:50%;color:#fff}.social-links svg{width:19px;height:19px;fill:currentColor;stroke:currentColor;stroke-width:1.5}.social-links svg rect,.social-links svg circle{fill:none}@media(max-width:700px){.navlinks{display:none}.grid{grid-template-columns:1fr}.page{margin:45px auto}}</style></head><body>
<nav class="nav"><a class="logo" href="<?=BASE_URL?>/#home">NEPAL DISASTER ARCHIVE</a><div class="navlinks"><a href="<?=BASE_URL?>/#home">Home</a><a href="<?=BASE_URL?>/#stories">Stories</a><a href="<?=BASE_URL?>/#hazards">Categories</a><a href="<?=BASE_URL?>/#explore">Explore</a><a href="<?=BASE_URL?>/resources.php">Emergency Help</a><a href="<?=BASE_URL?>/preparedness.php">Guides</a><a href="<?=BASE_URL?>/about.php">About Us</a><a href="<?=BASE_URL?>/admin/login.php">Editor Login</a></div></nav>
<main class="page"><div class="eyebrow">About the project</div><h1>Understanding Nepal's disaster history.</h1><p class="lead">Nepal Disaster Archive is a public database documenting natural disasters across Nepal to support research, learning, historical understanding, and preparedness.</p><div class="grid"><section class="block"><h2>Data Sources</h2><p>Records are developed from Government of Nepal and NDRRMA reports, the Department of Hydrology and Meteorology, ICIMOD, USGS, UNESCO, scientific research, and other cited authorities.</p></section><section class="block"><h2>Coverage</h2><p>The archive covers earthquakes, floods, landslides, avalanches, glacial lake outburst floods, storms, lightning, drought, heat waves, cold waves, tornadoes, and wildfires across Nepal's recorded history.</p></section><section class="block"><h2>Methodology</h2><p>Records are collected, checked against available sources, cleaned for consistent fields, and categorized by hazard, province, district, date, and location. Uncertain historical figures are identified rather than presented as exact facts.</p></section><section class="block">
    <h2>Disclaimer</h2><p>Historical records may be incomplete, conflicting, or limited by the sources that survive. Casualty figures, dates, magnitudes, and damage estimates may vary between sources. Please review the references attached to each story.</p></section><section class="block">
        <h2>Contact / Feedback</h2>
        <p>Use the <a href="<?=BASE_URL?>/admin/login.php">editor contact channel</a>  to report corrections, suggest records, or contribute reliable information for review.</p>
    </section>
    
    
    <section class="block"><h2>Last Updated</h2><p><?=e($lastUpdated ? date('F j, Y',strtotime($lastUpdated)) : 'Not yet available')?></p><p></p></section></div><a class="back" href="<?=BASE_URL?>/">← Back to archive</a></main>
<footer class="footer"><strong>NEPAL DISASTER ARCHIVE</strong><p>Documenting Disasters. Building Resilience - An AcademiX Digital Initiative</p>
<p> Content is provided for research and educational use with attribution.</p>
<div class="social-links"><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook"><svg viewBox="0 0 24 24"><path d="M14 8h3V4h-3c-3.3 0-5 1.8-5 5v3H6v4h3v8h4v-8h3.2l.8-4H13V9c0-.7.3-1 1-1z"/></svg></a><a href="https://www.instagram.com/academix_digital/" target="_blank" rel="noopener noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/></svg></a></div></footer></body></html>
