<?php
require_once __DIR__.'/config/config.php';
$submissionSent=false;$submissionError='';
if(($_SERVER['REQUEST_METHOD']??'GET')==='POST'&&isset($_POST['submit_story'])){
 verify_csrf();
 $title=trim($_POST['title']??'');$name=trim($_POST['storyteller_name']??'');$role=trim($_POST['storyteller_role']??'');$email=trim($_POST['email']??'');$location=trim($_POST['location']??'');$eventDate=trim($_POST['event_date']??'');$content=trim($_POST['story_content']??'');$anonymous=isset($_POST['is_anonymous'])?1:0;
 if(trim($_POST['website']??'')!=='')$submissionError='Your submission could not be accepted.';
 elseif($title===''||$content===''||!isset($_POST['consent_confirmed']))$submissionError='Please complete the title, story, and consent confirmation.';
 elseif($email!==''&&!filter_var($email,FILTER_VALIDATE_EMAIL))$submissionError='Please enter a valid email address or leave it blank.';
 else{
  $imagePath=null;
  if(!empty($_FILES['photo']['name'])&&is_uploaded_file($_FILES['photo']['tmp_name'])){$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['photo']['tmp_name']);if(!isset($allowed[$mime])||$_FILES['photo']['size']>5242880)$submissionError='Photos must be JPG, PNG, or WebP files up to 5 MB.';else{$dir=__DIR__.'/uploads/story-submissions';if(!is_dir($dir))mkdir($dir,0755,true);$file=bin2hex(random_bytes(12)).'.'.$allowed[$mime];if(move_uploaded_file($_FILES['photo']['tmp_name'],$dir.'/'.$file))$imagePath='uploads/story-submissions/'.$file;}}
  if($submissionError===''){try{$s=db()->prepare('INSERT INTO story_submissions(title,storyteller_name,storyteller_role,email,location,event_date,story_content,image_path,is_anonymous,consent_confirmed) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->execute([$title,$name?:null,$role?:null,$email?:null,$location?:null,$eventDate?:null,$content,$imagePath,$anonymous,1]);$submissionSent=true;}catch(Throwable $e){$submissionError='We could not receive your story right now. Please try again later.';}}
 }
}
$q=trim($_GET['q']??'');$province=trim($_GET['province']??'');$district=trim($_GET['district']??'');$where="WHERE s.status='PUBLISHED' AND s.story_type='HUMAN'";$params=[];
if($q!==''){$where.=' AND (s.title LIKE ? OR s.storyteller_name LIKE ? OR s.storyteller_role LIKE ? OR s.location LIKE ? OR s.summary LIKE ? OR s.content LIKE ?)';for($i=0;$i<6;$i++)$params[]="%$q%";}
if($province!==''){$where.=' AND s.province=?';$params[]=$province;}if($district!==''){$where.=' AND s.district=?';$params[]=$district;}
$st=db()->prepare("SELECT s.*,c.name category FROM stories s LEFT JOIN categories c ON c.id=s.category_id $where ORDER BY s.featured DESC,COALESCE(s.event_date,'1000-01-01') DESC,s.created_at DESC");$st->execute($params);$stories=$st->fetchAll();$locationData=nepal_locations();$districts=array_values(array_unique(array_merge(...array_values($locationData))));sort($districts);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Human Stories Archive - Nepal Disaster Archive</title><style>:root{--ink:#17202a;--paper:#f7f3ed;--red:#9e2b25;--line:#d9d0c6}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:Georgia,serif}.nav{position:sticky;top:0;background:#111820;color:#fff;z-index:2;padding:15px 5%;display:flex;align-items:center;gap:25px;font:13px Arial}.nav a{color:#fff;text-decoration:none}.logo{font-weight:900;letter-spacing:2px}.navlinks{margin-left:auto;display:flex;gap:18px}.hero{padding:85px 7% 65px;background:#263d3a;color:#fff}.hero h1{font-size:clamp(44px,7vw,82px);line-height:.95;max-width:850px;margin:15px 0 25px}.hero p{font-size:21px;line-height:1.6;color:#dce4df;max-width:750px}.wrap{width:min(1150px,90%);margin:auto}.section{padding:65px 0}.filters,.submission-form{display:flex;flex-wrap:wrap;gap:10px;margin:25px 0}.filters input,.filters select,.filters button,.submission-form input,.submission-form textarea{padding:13px;border:1px solid var(--line);background:#fff;border-radius:6px;font:15px Arial}.filters button,.submission-form button{background:var(--red);color:#fff;border:0;border-radius:6px;padding:13px 20px;font:700 15px Arial}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:20px}.card,.submission{background:#fff;border:1px solid var(--line);padding:25px;border-radius:8px}.card h2{font-size:27px;line-height:1.1;margin:12px 0}.card p,.submission p{color:#555;line-height:1.7}.meta{font:800 12px Arial;text-transform:uppercase;letter-spacing:1px;color:var(--red)}.byline{font:700 13px Arial;color:#53605c}.read{color:var(--red);font:700 14px Arial;text-decoration:none}.submission{margin-top:70px;max-width:850px}.submission h2{font-size:36px;margin-top:0}.submission-form{display:grid;grid-template-columns:1fr 1fr}.submission-form .full{grid-column:1/-1}.submission-form textarea{min-height:220px;resize:vertical}.submission-form label{font:14px Arial;display:block}.submission-form input[type=checkbox]{width:auto;margin-right:8px}.submission-form .trap{display:none}.notice{padding:13px 16px;border-left:4px solid var(--red);background:#f2e5dc;font:15px Arial}@media(max-width:800px){.navlinks{display:none}.cards,.submission-form{grid-template-columns:1fr}.submission-form .full{grid-column:auto}}</style></head><body>
<nav class="nav"><a class="logo" href="<?=BASE_URL?>/">NEPAL DISASTER ARCHIVE</a><div class="navlinks"><a href="<?=BASE_URL?>/">Disaster archive</a><a href="<?=BASE_URL?>/human-stories.php">Human stories</a><a href="<?=BASE_URL?>/resources.php">Emergency help</a><a href="<?=BASE_URL?>/preparedness.php">Guides</a><a href="<?=BASE_URL?>/about.php">About us</a></div></nav>
<header class="hero"><div class="wrap"><div class="meta" style="color:#e5b5a9">Human experience · Nepal</div><h1>Human Stories Archive</h1><p>The voices, memories, courage, loss, and recovery behind Nepal's disasters. These accounts preserve lived experience alongside the historical record.</p></div></header>
<main class="section"><div class="wrap"><form class="filters"><input name="q" value="<?=e($q)?>" placeholder="Search people, places, stories..."><select name="province"><option value="">All provinces</option><?php foreach(array_keys($locationData) as $item):?><option value="<?=e($item)?>" <?=$province===$item?'selected':''?>><?=e($item)?></option><?php endforeach;?></select><select name="district"><option value="">All districts</option><?php foreach($districts as $item):?><option value="<?=e($item)?>" <?=$district===$item?'selected':''?>><?=e($item)?></option><?php endforeach;?></select><button>Find stories</button></form><div class="cards"><?php foreach($stories as $story):?><article class="card"><div class="meta"><?=e($story['year_label']?:'Personal account')?> · <?=e($story['location']?:'Nepal')?></div><h2><?=e($story['title'])?></h2><?php if($story['storyteller_name']):?><div class="byline">Told by <?=e($story['storyteller_name'])?><?= $story['storyteller_role']?' · '.e($story['storyteller_role']):''?></div><?php endif;?><p><?=e($story['summary']?:mb_substr(strip_tags($story['content']),0,200).'...')?></p><a class="read" href="<?=BASE_URL?>/story.php?slug=<?=urlencode($story['slug'])?>">Read this account →</a></article><?php endforeach;?></div><?php if(!$stories):?><p>No published human stories match these filters yet.</p><?php endif;?>
<section class="submission" id="submit-story"><div class="meta">Share your experience</div><h2>Submit Your Story</h2><p>Write clearly about what happened, what you experienced, and how your community responded. Submissions are reviewed by our editors before publication.</p><?php if($submissionSent):?><div class="notice">Thank you. Your story has been sent to the archive team for review.</div><?php elseif($submissionError):?><div class="notice"><?=e($submissionError)?></div><?php endif;?><form class="submission-form" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="submit_story" value="1"><div class="trap"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><label>Story title *<input name="title" required></label><label>Your name<input name="storyteller_name" placeholder="Optional"></label><label>Your role<input name="storyteller_role" placeholder="Survivor, rescuer, volunteer..."></label><label>Email<input type="email" name="email" placeholder="Optional, for editor follow-up"></label><label>Location<input name="location" placeholder="District or community"></label><label>Date of event<input type="date" name="event_date"></label><label class="full">Your story *<textarea name="story_content" required placeholder="Tell us what happened in your own words..."></textarea></label><label class="full">Optional photo<input type="file" name="photo" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG, or WebP up to 5 MB.</small></label><label class="full"><input type="checkbox" name="is_anonymous"> Publish my name as Anonymous</label><label class="full"><input type="checkbox" name="consent_confirmed" required> I confirm that I have permission to submit this account and understand that editors may contact me, edit it for clarity, or decline publication. *</label><button class="full" type="submit">Send story for review</button></form></section></div></main></body></html>
