<?php
require_once __DIR__.'/config/config.php';
$lang='en';
echo '<style>.links span,.links a[href*="about.php"]{display:none}</style>';
$text=$lang==='ne'?['title'=>'आपतकालीन तयारी निर्देशिका','eyebrow'=>'तयार रहनुहोस्','lead'=>'प्रकोपअघि, प्रकोपको समयमा र त्यसपछि परिवार तथा समुदायलाई सुरक्षित राख्न आधारभूत कदमहरू।','home'=>'होम','resources'=>'आपतकालीन स्रोतहरू','archive'=>'अभिलेख','language'=>'भाषा']:['title'=>'Preparedness Guides','eyebrow'=>'Be prepared','lead'=>'Practical steps to help families and communities stay safer before, during, and after a disaster.','home'=>'Home','resources'=>'Emergency resources','archive'=>'Archive','language'=>'Language'];
$guides=$lang==='ne' ? [
 ['title'=>'भूकम्प','before'=>'भारी सामान तल राख्नुहोस्, आपतकालीन झोला तयार राख्नुहोस् र परिवार भेट्ने स्थान तय गर्नुहोस्।','during'=>'झुक्नुहोस्, छोपिनुहोस् र समातिरहनुहोस्। झ्याल, लिफ्ट र क्षतिग्रस्त भवनबाट टाढा रहनुहोस्।','after'=>'ग्यास तथा बिजुलीको जोखिम जाँच्नुहोस्, अफवाह नफैलाउनुहोस् र आधिकारिक सूचनाको पालना गर्नुहोस्।'],
 ['title'=>'बाढी','before'=>'स्थानीय बाढी जोखिम बुझ्नुहोस्, महत्वपूर्ण कागजात सुरक्षित राख्नुहोस् र निकासी मार्ग पहिल्यै जान्नुहोस्।','during'=>'उच्च स्थानतर्फ जानुहोस्। बाढीको पानीमा हिँड्ने वा सवारी चलाउने प्रयास नगर्नुहोस्।','after'=>'फोहोर पानीबाट टाढा रहनुहोस् र सुरक्षित नभएसम्म घर वा सडकमा नफर्कनुहोस्।'],
 ['title'=>'पहिरो','before'=>'पहिरो जोखिम क्षेत्र पहिचान गर्नुहोस् र वर्षायाममा स्थानीय सूचना तथा सडक अवस्था हेर्नुहोस्।','during'=>'चिरा, ढुंगा खस्ने वा असामान्य आवाज आएमा तुरुन्त सुरक्षित खुला स्थानतर्फ जानुहोस्।','after'=>'पहिरो क्षेत्रमा पुनः नजानुहोस्; उद्धार टोलीको निर्देशन पर्खनुहोस्।'],
 ['title'=>'चट्याङ र हुरी','before'=>'मौसम पूर्वानुमान हेर्नुहोस् र बाहिरी काम सुरक्षित समयमा गर्नुहोस्।','during'=>'भवनभित्र पस्नुहोस्। रुख, धातुका संरचना, पानी र खुला मैदानबाट टाढा रहनुहोस्।','after'=>'तार, पोल र क्षतिग्रस्त संरचनाबाट टाढा रहनुहोस्।']
] : [
 ['title'=>'Earthquake','before'=>'Secure heavy objects, prepare an emergency bag, and agree on a family meeting point.','during'=>'Drop, cover, and hold on. Stay away from windows, elevators, and damaged buildings.','after'=>'Check for gas and electrical hazards, avoid rumors, and follow official instructions.'],
 ['title'=>'Flood','before'=>'Learn local flood risks, protect important documents, and identify evacuation routes.','during'=>'Move to higher ground. Never walk or drive through floodwater.','after'=>'Avoid contaminated water and do not return until authorities say it is safe.'],
 ['title'=>'Landslide','before'=>'Identify landslide-prone areas and monitor rainfall, warnings, and road conditions.','during'=>'Leave immediately if you see cracks, falling rocks, or hear unusual sounds.','after'=>'Stay away from the slide area and wait for responders to give clearance.'],
 ['title'=>'Lightning and storms','before'=>'Check weather forecasts and plan outdoor work around severe-weather periods.','during'=>'Move indoors. Stay away from trees, metal structures, water, and open ground.','after'=>'Avoid downed wires, poles, and damaged structures.']
];
?><!doctype html><html lang="<?= $lang==='ne'?'ne':'en'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($text['title'])?> - Nepal Disaster Archive</title><style>body{margin:0;background:#f7f3ed;color:#17202a;font-family:Georgia,serif}.nav{background:#111820;color:#fff;padding:15px 5%;display:flex;align-items:center;gap:22px;font:13px Arial}.nav a{color:#fff;text-decoration:none}.logo{font-weight:900;letter-spacing:2px}.links{margin-left:auto;display:flex;gap:16px;align-items:center}.page{width:min(1050px,90%);margin:70px auto}.eyebrow{color:#9e2b25;font:800 13px Arial;text-transform:uppercase;letter-spacing:1px}.page h1{font-size:clamp(42px,7vw,76px);line-height:1;margin:15px 0}.lead{font-size:20px;line-height:1.6;color:#555;max-width:800px}.guides{display:grid;gap:22px;margin-top:45px}.guide{background:#fff;border:1px solid #d9d0c6;border-radius:8px;padding:25px}.guide h2{margin:0 0 20px;font-size:27px}.steps{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.steps h3{font:700 13px Arial;color:#9e2b25;text-transform:uppercase}.steps p{line-height:1.7;color:#555}@media(max-width:800px){.steps{grid-template-columns:1fr}.links{display:none}}</style></head><body><nav class="nav"><a class="logo" href="<?=BASE_URL?>/">NEPAL DISASTER ARCHIVE</a><div class="links"><a href="<?=BASE_URL?>/"><?=e($text['home'])?></a><a href="<?=BASE_URL?>/resources.php?lang=<?=$lang?>"><?=e($text['resources'])?></a><a href="<?=BASE_URL?>/about.php?lang=<?=$lang?>"><?=e($text['archive'])?></a><span><?=e($text['language'])?>: <a href="?lang=en">EN</a> / <a href="?lang=ne">ने</a></span></div></nav><main class="page"><div class="eyebrow"><?=e($text['eyebrow'])?></div><h1><?=e($text['title'])?></h1><p class="lead"><?=e($text['lead'])?></p><div class="guides"><?php foreach($guides as $guide):?><article class="guide"><h2><?=e($guide['title'])?></h2><div class="steps"><div><h3><?= $lang==='ne'?'अघि':'Before'?></h3><p><?=e($guide['before'])?></p></div><div><h3><?= $lang==='ne'?'समयमा':'During'?></h3><p><?=e($guide['during'])?></p></div><div><h3><?= $lang==='ne'?'पछि':'After'?></h3><p><?=e($guide['after'])?></p></div></div></article><?php endforeach;?></div></main></body></html>
