<?php
require_once __DIR__.'/config/config.php';
$lang='en';
echo '<style>.links span,.links a[href*="about.php"]{display:none}</style>';
$text=$lang==='ne'?[
 'title'=>'आपतकालीन स्रोतहरू','eyebrow'=>'तुरुन्त सहयोग','lead'=>'आपतकालमा प्रयोग गर्न मिल्ने आधिकारिक सम्पर्क र सहयोग सेवाहरू। स्थानीय अवस्था र आधिकारिक सूचनालाई सधैं प्राथमिकता दिनुहोस्।','home'=>'होम','guides'=>'तयारी निर्देशिका','archive'=>'अभिलेख','language'=>'भाषा','call'=>'कल गर्नुहोस्','note'=>'सम्पर्क नम्बर र सेवा उपलब्धता परिवर्तन हुन सक्छ। प्रयोग गर्नुअघि स्थानीय निकाय वा आधिकारिक स्रोतबाट पुष्टि गर्नुहोस्।'
]:[
 'title'=>'Emergency Resources','eyebrow'=>'Immediate help','lead'=>'Official contacts and practical services for emergencies in Nepal. Always follow local instructions and current official alerts.','home'=>'Home','guides'=>'Preparedness guides','archive'=>'Archive','language'=>'Language','call'=>'Call','note'=>'Phone numbers and service availability can change. Confirm details with local authorities or official sources before relying on them.'
];
$resources=$lang==='ne'?[
 ['name'=>'नेपाल प्रहरी','number'=>'100','detail'=>'तत्काल सुरक्षा र प्रहरी सहयोग'],['name'=>'दमकल','number'=>'101','detail'=>'आगलागी तथा उद्धार सहयोग'],['name'=>'एम्बुलेन्स','number'=>'102','detail'=>'चिकित्सा आपतकालीन सेवा'],['name'=>'ट्राफिक प्रहरी','number'=>'103','detail'=>'सडक दुर्घटना र ट्राफिक सहयोग'],['name'=>'स्थानीय जिल्ला प्रशासन','number'=>'स्थानीय नम्बर पुष्टि गर्नुहोस्','detail'=>'निकासी, राहत र स्थानीय समन्वय'],['name'=>'नजिकको अस्पताल','number'=>'स्थानीय सेवा खोज्नुहोस्','detail'=>'आपतकालीन उपचार र स्वास्थ्य सहायता']
]:[
 ['name'=>'Nepal Police','number'=>'100','detail'=>'Immediate security and police assistance'],['name'=>'Fire and Rescue','number'=>'101','detail'=>'Fire response and rescue assistance'],['name'=>'Ambulance','number'=>'102','detail'=>'Medical emergency transport'],['name'=>'Traffic Police','number'=>'103','detail'=>'Road accidents and traffic emergencies'],['name'=>'District Administration','number'=>'Confirm local number','detail'=>'Evacuation, relief, and local coordination'],['name'=>'Nearest hospital','number'=>'Find local service','detail'=>'Emergency treatment and medical support']
];
?><!doctype html><html lang="<?= $lang==='ne'?'ne':'en'?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($text['title'])?> - Nepal Disaster Archive</title><style>body{margin:0;background:#f7f3ed;color:#17202a;font-family:Georgia,serif}.nav{background:#111820;color:#fff;padding:15px 5%;display:flex;align-items:center;gap:22px;font:13px Arial}.nav a{color:#fff;text-decoration:none}.logo{font-weight:900;letter-spacing:2px}.links{margin-left:auto;display:flex;gap:16px;align-items:center}.page{width:min(1100px,90%);margin:70px auto}.eyebrow{color:#9e2b25;font:800 13px Arial;text-transform:uppercase;letter-spacing:1px}.page h1{font-size:clamp(42px,7vw,76px);line-height:1;margin:15px 0}.lead{font-size:20px;line-height:1.6;color:#555;max-width:800px}.resources{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:45px}.resource{background:#fff;border:1px solid #d9d0c6;border-radius:8px;padding:24px}.resource h2{margin:0 0 10px;font-size:22px}.number{display:block;color:#9e2b25;font:bold 28px Arial;margin-bottom:10px}.call{display:inline-block;margin-top:18px;color:#9e2b25;font:bold 13px Arial;text-decoration:none}.note{margin-top:35px;padding:18px;border-left:3px solid #9e2b25;background:#eee9e2;font:14px Arial;color:#555}@media(max-width:800px){.resources{grid-template-columns:1fr}.links{display:none}}</style></head><body><nav class="nav"><a class="logo" href="<?=BASE_URL?>/">NEPAL DISASTER ARCHIVE</a><div class="links"><a href="<?=BASE_URL?>/"><?=e($text['home'])?></a><a href="<?=BASE_URL?>/preparedness.php?lang=<?=$lang?>"><?=e($text['guides'])?></a><a href="<?=BASE_URL?>/about.php?lang=<?=$lang?>"><?=e($text['archive'])?></a><span><?=e($text['language'])?>: <a href="?lang=en">EN</a> / <a href="?lang=ne">ने</a></span></div></nav><main class="page"><div class="eyebrow"><?=e($text['eyebrow'])?></div><h1><?=e($text['title'])?></h1><p class="lead"><?=e($text['lead'])?></p><div class="resources"><?php foreach($resources as $resource):?><article class="resource"><h2><?=e($resource['name'])?></h2><span class="number"><?=e($resource['number'])?></span><p><?=e($resource['detail'])?></p><?php if(ctype_digit($resource['number'])):?><a class="call" href="tel:<?=e($resource['number'])?>"><?=e($text['call'])?> <?=e($resource['number'])?></a><?php endif;?></article><?php endforeach;?></div><p class="note"><?=e($text['note'])?></p></main></body></html>
