<?php
require_once __DIR__.'/config/config.php';
$slug=trim($_GET['slug']??'');
$s=db()->prepare("SELECT s.*,c.name category FROM stories s LEFT JOIN categories c ON c.id=s.category_id WHERE s.slug=? AND s.status='PUBLISHED' LIMIT 1");$s->execute([$slug]);$story=$s->fetch();
if(!$story){http_response_code(404);exit('Story not found.');}
$paragraphs=preg_split("/\R{2,}/",trim($story['content']));
$gallery=[];$structuredSources=[];$correctionSent=false;
try{$g=db()->prepare('SELECT * FROM story_images WHERE story_id=? ORDER BY sort_order,id');$g->execute([$story['id']]);$gallery=$g->fetchAll();$src=db()->prepare('SELECT * FROM story_sources WHERE story_id=? ORDER BY id');$src->execute([$story['id']]);$structuredSources=$src->fetchAll();track_event('view',(int)$story['id']);}catch(Throwable $e){}
if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['correction_message'])){verify_csrf();$message=trim($_POST['correction_message']);if($message!==''){try{$r=db()->prepare('INSERT INTO correction_reports(story_id,name,email,message) VALUES(?,?,?,?)');$r->execute([(int)$story['id'],trim($_POST['correction_name']??''),trim($_POST['correction_email']??''),$message]);$correctionSent=true;}catch(Throwable $e){}}}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($story['title'])?> — Nepal Disaster Archive</title>
<style>body{margin:0;background:#f7f3ed;color:#17202a;font-family:Georgia,serif}.nav{position:sticky;top:0;background:#111820;color:#fff;z-index:10;padding:15px 5%;display:flex;align-items:center;gap:25px;font-family:Arial}.nav a{color:#fff;text-decoration:none;font-size:13px}.logo{font-weight:900;letter-spacing:2px}.navlinks{margin-left:auto;display:flex;gap:18px}.article{max-width:850px;margin:70px auto;padding:0 25px}.meta{color:#9e2b25;font:800 13px Arial;text-transform:uppercase;letter-spacing:1px}.article h1{font-size:clamp(42px,7vw,72px);line-height:1;margin:15px 0}.dek{font-size:21px;color:#555;line-height:1.6}.facts{display:flex;flex-wrap:wrap;gap:12px;margin:30px 0}.fact{background:#fff;border:1px solid #ddd0c5;padding:15px;border-radius:8px;font-family:Arial}.fact b{display:block;font-size:12px;color:#777}.body{font-size:19px;line-height:1.85}.body p{margin:0 0 24px}.sources{border-top:2px solid #9e2b25;margin-top:45px;padding-top:20px;font:15px Arial;white-space:pre-line;color:#555}.share-tools{display:flex;flex-wrap:wrap;gap:10px;margin:25px 0 35px;font-family:Arial}.share-tools button,.share-tools a{border:1px solid #cfc4b8;background:#fff;color:#17202a;border-radius:6px;padding:10px 13px;font:700 13px Arial;text-decoration:none;cursor:pointer}.share-tools button:hover,.share-tools a:hover{background:#9e2b25;border-color:#9e2b25;color:#fff}.footer{background:#111820;color:#d8dde0;padding:45px 7%;font-family:Arial}.social-links{display:flex;gap:14px;margin-top:20px}.social-links a{display:inline-flex;width:38px;height:38px;align-items:center;justify-content:center;border:1px solid #59636a;border-radius:50%;color:#fff}.social-links a:hover{background:#9e2b25;border-color:#9e2b25}.social-links svg{width:19px;height:19px;fill:currentColor;stroke:currentColor;stroke-width:1.5}.social-links svg rect,.social-links svg circle{fill:none}.social-links svg .icon-fill{fill:currentColor;stroke:none}.story-cover{display:block;width:100%;max-height:520px;object-fit:cover;border-radius:8px;margin-bottom:30px}@media(max-width:850px){.navlinks{display:none}}@media print{body{background:#fff}.nav,.share-tools{display:none}.article{max-width:none;margin:0;padding:0}.footer{margin-top:40px;padding:25px 0;color:#17202a;background:#fff;border-top:2px solid #17202a}.footer strong{color:#17202a}.social-links{display:none}}</style></head><body>
<nav class="nav"><a class="logo" href="<?=BASE_URL?>/#home">NEPAL DISASTER ARCHIVE</a><div class="navlinks"><a href="<?=BASE_URL?>/#home">Home</a><a href="<?=BASE_URL?>/#stories">Stories</a><a href="<?=BASE_URL?>/#hazards">Categories</a><a href="<?=BASE_URL?>/#explore">Explore</a><a href="<?=BASE_URL?>/resources.php">Emergency Help</a><a href="<?=BASE_URL?>/preparedness.php">Guides</a><a href="<?=BASE_URL?>/about.php">About Us</a><a href="<?=BASE_URL?>/admin/login.php">Editor Login</a></div></nav><article class="article"><div class="meta"><?=e($story['category']??'Natural Disaster')?> · <?=e($story['year_label'])?></div><h1><?=e($story['title'])?></h1><p class="dek"><?=e($story['summary'])?></p>
<div class="share-tools" aria-label="Story sharing and download tools"><a href="https://wa.me/?text=<?=urlencode($story['title'].' '.(BASE_URL.'/story.php?slug='.$story['slug']))?>" target="_blank" rel="noopener noreferrer">WhatsApp</a><a href="https://www.facebook.com/sharer/sharer.php?u=<?=urlencode(BASE_URL.'/story.php?slug='.$story['slug'])?>" target="_blank" rel="noopener noreferrer">Facebook</a><a href="mailto:?subject=<?=urlencode($story['title'])?>&body=<?=urlencode(BASE_URL.'/story.php?slug='.$story['slug'])?>">Email</a><button type="button" id="copy-link">Copy link</button><button type="button" onclick="window.print()">Print / Save PDF</button></div>
<div class="facts"><?php foreach([['Date',$story['event_date']],['Location',$story['location']],['Magnitude',$story['magnitude']],['Deaths',$story['deaths']],['Injuries',$story['injuries']]] as $f):if($f[1]):?><div class="fact"><b><?=e($f[0])?></b><?=e($f[1])?></div><?php endif;endforeach;?></div>
<div class="body"><?php foreach($paragraphs as $p):?><p><?=nl2br(e($p))?></p><?php endforeach;?></div>
<style>.footer-grid,.footer-bottom{display:none}.footer{display:flex;align-items:center;justify-content:space-between;gap:25px;flex-wrap:wrap}.footer-about{color:#fff;text-decoration:none;font:700 13px Arial}.footer-about:hover{text-decoration:underline}</style>
<?php if($story['impact']):?><h2>Impact</h2><div class="body"><p><?=nl2br(e($story['impact']))?></p></div><?php endif;?>
<?php if($structuredSources):?><div class="sources"><strong>Verified sources</strong><?php foreach($structuredSources as $source):?><p><a href="<?=e($source['url']??'')?>" target="_blank" rel="noopener noreferrer"><?=e($source['title'])?></a><?php if($source['publisher']):?> · <?=e($source['publisher'])?><?php endif;?><?php if($source['verified']):?> · Verified<?php endif;?></p><?php endforeach;?></div><?php endif;?>
<?php if($gallery):?><div class="gallery"><?php foreach($gallery as $image):?><figure><img src="<?=BASE_URL?>/<?=e($image['image_path'])?>" alt="<?=e($image['caption']?:$story['title'])?>"><figcaption><?=e($image['caption']??'')?> <?php if($image['credit']):?><small><?=e($image['credit'])?></small><?php endif;?></figcaption></figure><?php endforeach;?></div><?php endif;?>
<section class="correction"><h2>Report a correction</h2><?php if($correctionSent):?><p>Thank you. Your correction has been submitted for review.</p><?php else:?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input name="correction_name" placeholder="Your name"><input type="email" name="correction_email" placeholder="Email (optional)"><textarea name="correction_message" required placeholder="What should be corrected?"></textarea><button type="submit">Send correction</button></form><?php endif;?></section>
<?php if($story['sources']):?><div class="sources"><strong>Sources / references</strong><br><br><?=e($story['sources'])?></div><?php endif;?>
<?php if(!empty($story['image_path'])):?><img class="story-cover" src="<?=BASE_URL?>/<?=e($story['image_path'])?>" alt="<?=e($story['title'])?>"><?php endif;?></article>
   
    <footer class="footer clean-footer"><div><strong>NEPAL DISASTER ARCHIVE</strong><p>Documenting Disasters. Building Resilience - An AcademiX Digital Initiative</p></div><a class="footer-about" href="<?=BASE_URL?>/about.php">About Us</a>
    <div class="social-links" aria-label="Social media links"><a href="https://www.facebook.com/" target="_blank" rel="noopener noreferrer" aria-label="Facebook" title="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 1.8-5 5v3H6v4h3v8h4v-8h3.2l.8-4H13V9c0-.7.3-1 1-1z"/></svg></a><a href="https://www.instagram.com/academix_digital/" target="_blank" rel="noopener noreferrer" aria-label="Instagram" title="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" class="icon-fill"/></svg></a></div></footer>
        
        
        
        <script>document.getElementById('copy-link').addEventListener('click',function(){var button=this;navigator.clipboard.writeText(window.location.href).then(function(){button.textContent='Link copied';setTimeout(function(){button.textContent='Copy link'},1800)}).catch(function(){window.prompt('Copy this story link:',window.location.href)})});</script></body></html>