USE nepal_disaster_archive;

INSERT IGNORE INTO stories
(title, slug, category_id, event_date, year_label, location, summary, content, deaths, injuries, magnitude, impact, sources, featured, status)
VALUES
('1255 Kathmandu Valley Earthquake','1255-kathmandu-valley-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1255-06-07','1255','Kathmandu Valley','The earliest major earthquake in Nepal for which a historical record survives.','On 7 June 1255 a major earthquake struck the Kathmandu Valley. Historical accounts describe severe destruction of buildings and temples and a very large loss of life. NSET identifies it as the first recorded earthquake in Nepal and reports that King Abhaya Malla died. The commonly cited magnitude of about 7.7 is a reconstruction, not an instrumental measurement.','Historical account: about one third of Kathmandu population; exact number uncertain','Not reliably known','Estimated about 7.7','Buildings and temples collapsed or were severely damaged; wider humanitarian hardship followed.','NSET chronological historical earthquake catalogue',1,'PUBLISHED'),

('1260 Nepal Earthquake','1260-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1260-01-01','1260','Kathmandu Valley and surrounding areas','A major earthquake recorded during the Malla period caused heavy loss of life and property.','The 1260 earthquake is one of the earliest major earthquakes in Nepal’s surviving historical record. Contemporary information is limited. NSET records heavy loss of life and property and notes epidemic and famine in the aftermath. Exact date, magnitude and casualty figures are not reliably established.','Heavy loss of life reported; exact number unknown','Unknown','Not reliably established','Buildings and temples were damaged or destroyed and wider social hardship was reported.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1408 Nepal Earthquake','1408-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1408-09-01','1408','Kathmandu Valley and surrounding areas','A major historical earthquake caused heavy damage to temples, buildings and settlements.','Historical records place a major earthquake in August or September 1408. NSET records destruction of the Rato Machhindranath temple, damage to many buildings and temples, ground cracks and heavy loss of life and livestock. The exact day and scientific magnitude remain uncertain.','Heavy loss of life reported; exact number unknown','Unknown','Estimated about 7.0 in NSET historical catalogue','Temples, buildings, land and livestock were affected.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1681 Nepal Earthquake','1681-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1681-12-01','1681','Kathmandu Valley and Nepal','A major historical earthquake caused loss of life and damage to buildings and temples.','Historical records identify a significant earthquake around December 1681 or January 1682. Available documentation is limited, but NSET records loss of life and property and damage or destruction of buildings and temples.','Heavy loss of life reported; exact number unknown','Unknown','Not reliably established','Historic buildings and temples were damaged or destroyed.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1767 Nepal Earthquake Sequence','1767-nepal-earthquake-sequence',(SELECT id FROM categories WHERE slug='earthquake'),'1767-06-01','1767','Nepal including Kathmandu Valley','A significant 1767 earthquake sequence included numerous shocks and aftershocks.','NSET records about 21 shocks and aftershocks within roughly 24 hours in June-July 1767. Surviving records do not support a reliable modern magnitude or casualty total.','Not reliably known','Not reliably known','Not established','Repeated shaking affected buildings and communities.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1810 Nepal Earthquake','1810-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1810-05-01','1810','Nepal and Kathmandu Valley','The 1810 earthquake caused moderate to heavy human and property losses.','A major earthquake was recorded in May 1810. NSET describes moderate to heavy loss of life and property. No reliable instrumental magnitude or precise casualty count exists.','Moderate to heavy loss reported; exact number unknown','Unknown','Not reliably established','Buildings and property were damaged.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1823 Nepal Earthquake','1823-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1823-01-01','1823','Nepal','A historical earthquake recorded in 1823 caused loss of life and property, although details are limited.','NSET records a 1823 earthquake with minor loss of life and property. Exact date, magnitude and geographic extent are uncertain.','Minor loss reported; exact number unknown','Unknown','Not established','Localized building and property damage was reported.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1833 Nepal Earthquake','1833-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1833-08-26','1833','Kathmandu Valley and central Nepal','The 1833 earthquake sequence was one of the most important pre-instrumental earthquakes in the Kathmandu Valley.','On 26 August 1833 a major earthquake sequence affected Kathmandu and surrounding regions. Historical accounts describe repeated strong shocks and substantial damage. NSET records 18,000 buildings and temples damaged in the broader sequence record. Another strong earthquake occurred on 25 September, with additional shocks in 1834. Modern magnitude estimates are reconstructed and vary.','Casualty estimates vary; no single authoritative total','Not reliably established','Historical estimates vary','About 18,000 buildings and temples were reported damaged in the NSET record.','NSET historical earthquake catalogue; historical and paleoseismic research',1,'PUBLISHED'),

('1834 Nepal Earthquake Sequence','1834-nepal-earthquake-sequence',(SELECT id FROM categories WHERE slug='earthquake'),'1834-07-11','1834','Kathmandu Valley and Nepal','Several strong shocks were recorded in 1834 following the destructive 1833 sequence.','Historical records list strong shocks on 11 July, 13 July and 26 September 1834, along with other tremors. NSET describes heavy loss of life and property.','Heavy loss reported; exact number unknown','Unknown','Not reliably established','Repeated earthquakes caused additional structural damage and prolonged disruption.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1934 Nepal-Bihar Earthquake','1934-nepal-bihar-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1934-01-15','1934','Kathmandu Valley, eastern Nepal and Bihar','The 1934 Nepal-Bihar earthquake was one of the most destructive earthquakes in modern South Asian history.','On 15 January 1934 a very large earthquake struck Nepal and northern Bihar. Kathmandu, Bhaktapur and Patan suffered severe structural damage. NSET’s historical table gives a magnitude of about 8.4, 8,519 deaths, 80,893 collapsed buildings and 126,355 damaged buildings. Other sources use different casualty boundaries, so totals should be identified by source.','NSET historical table: 8,519','Widespread; exact total uncertain','About 8.4 historical estimate','Homes, temples, palaces and public buildings collapsed or were damaged across Nepal and Bihar.','NSET historical earthquake catalogue; historical government records',1,'PUBLISHED'),

('1980 Bajhang Earthquake','1980-bajhang-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1980-08-04','1980','Bajhang, western Nepal','The 1980 Bajhang earthquake killed and injured hundreds and damaged thousands of buildings.','NSET records a magnitude of about 6.1, 46 deaths and 236 injuries. It also records 12,817 buildings/temples collapsed and 13,298 damaged.','46','236','About 6.1','Thousands of rural buildings were collapsed or damaged.','NSET historical earthquake catalogue',0,'PUBLISHED'),

('1988 Udayapur Earthquake','1988-udayapur-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1988-08-21','1988','Udayapur and eastern Nepal','The 1988 Udayapur earthquake caused widespread damage and hundreds of deaths in eastern Nepal.','On 21 August 1988 a major earthquake struck eastern Nepal. Historical Nepal earthquake records commonly report about 721 deaths and magnitude estimates around 6.5. Homes and public buildings were damaged and landslides occurred in affected areas.','About 721 reported','Hundreds reported','About 6.5','Homes, schools and other structures were damaged across eastern Nepal.','NSET earthquake catalogue; Government of Nepal; USGS',1,'PUBLISHED'),

('2011 Sikkim Earthquake and Nepal Impacts','2011-sikkim-earthquake-nepal',(SELECT id FROM categories WHERE slug='earthquake'),'2011-09-18','2011','Eastern Nepal and Sikkim region','The 2011 Sikkim earthquake was strongly felt across eastern Nepal.','On 18 September 2011 a magnitude 6.9 earthquake struck the Sikkim region. Strong shaking was experienced in eastern Nepal and landslides and localized structural damage occurred. It is best described as a regional earthquake with impacts in Nepal.','Nepal-only total varies by source','Reported injuries','Mw 6.9','Localized structural damage and landslides affected eastern Nepal.','USGS; Government of Nepal disaster reports',0,'PUBLISHED'),

('2015 Gorkha Earthquake','2015-gorkha-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'2015-04-25','2015','Gorkha, Kathmandu Valley and central Nepal','The Mw 7.8 Gorkha earthquake became the defining natural disaster of modern Nepal.','At 11:56 local time on 25 April 2015 a magnitude 7.8 earthquake began about 82 km northwest of Kathmandu. The earthquake generated strong shaking, landslides and avalanches. USGS reports about 9,000 fatalities, about 23,000 injuries, more than 500,000 destroyed houses and about 270,000 damaged houses. A magnitude 7.3 aftershock struck on 12 May. Heritage sites, schools, hospitals, roads and rural mountain communities were severely affected.','About 9,000','About 23,000','Mw 7.8; 12 May aftershock Mw 7.3','More than 500,000 houses destroyed and about 270,000 damaged according to USGS.','USGS; Government of Nepal Post Disaster Needs Assessment; UNESCO; NSET',1,'PUBLISHED'),

('2023 Jajarkot Earthquake','2023-jajarkot-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'2023-11-03','2023','Jajarkot and Rukum West, Karnali Province','The 2023 Jajarkot earthquake caused major casualties and housing destruction in western Nepal.','On 3 November 2023 a magnitude 5.7 earthquake struck western Nepal. Jajarkot and Rukum West suffered severe damage, especially where vulnerable homes could not withstand shaking. Official post-event assessments recorded 154 deaths and hundreds of injuries, with tens of thousands of houses damaged.','154','Hundreds','Magnitude 5.7','Homes collapsed or were damaged and essential services were disrupted.','USGS; Government of Nepal/NDRRMA post-earthquake assessments',1,'PUBLISHED'),

('1978 Tinau Basin Flood','1978-tinau-basin-flood',(SELECT id FROM categories WHERE slug='flood'),'1978-07-01','1978','Tinau Basin and southern Nepal','A major Tinau Basin flood is listed among Nepal’s historical flood disasters.','The 1978 Tinau Basin flood followed intense monsoon rainfall and caused damage along the river system. Nepal government disaster-risk records identify it as a major historical flood. Older reporting is incomplete, so unsupported precise casualty totals are not given here.','Historical totals vary','Not consistently documented','Severe monsoon flood','Settlements, farmland and infrastructure were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('1980 Koshi Flood','1980-koshi-flood',(SELECT id FROM categories WHERE slug='flood'),'1980-07-01','1980','Koshi Basin, eastern Nepal','A major Koshi flood in 1980 is recorded among Nepal’s important historical floods.','The Koshi is highly exposed to monsoon flooding because of its huge catchment, steep terrain, sediment loads and dense downstream settlement. The 1980 flood is listed in Nepal government historical disaster records, although exact casualty and economic-loss figures are not consistently reported in surviving summaries.','Historical totals vary','Not consistently documented','Severe monsoon flood','Settlements, farmland and infrastructure in the Koshi basin were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('1985 Tadi River Basin Flood','1985-tadi-river-basin-flood',(SELECT id FROM categories WHERE slug='flood'),'1985-07-01','1985','Tadi River Basin','The 1985 Tadi basin flood is recorded among Nepal’s major historical flood disasters.','Heavy monsoon rainfall produced destructive flooding in the Tadi River basin in 1985. Exact casualty and economic-loss figures are not consistently available in national historical summaries.','Historical totals vary','Not consistently documented','Severe monsoon flood','Settlements, agricultural land and river infrastructure were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('1987 Sunkoshi Basin Flood','1987-sunkoshi-basin-flood',(SELECT id FROM categories WHERE slug='flood'),'1987-07-01','1987','Sunkoshi Basin','The 1987 Sunkoshi basin flood is included in Nepal’s historical flood record.','The Sunkoshi is vulnerable to flash floods, landslides and debris flows. A major flood in 1987 is listed among the historical flood disasters recorded by Nepal authorities. Precise casualty figures are not consistently available in the national historical summaries.','Historical totals vary','Not consistently documented','Severe monsoon flood','River corridors, settlements, agriculture and transport infrastructure were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('1993 Central Nepal Flood and Landslide Disaster','1993-central-nepal-flood-landslide-disaster',(SELECT id FROM categories WHERE slug='flood'),'1993-07-19','1993','Central and southern Nepal','Exceptional monsoon rainfall produced catastrophic floods and landslides across central and southern Nepal.','In July 1993 exceptionally heavy monsoon rainfall triggered widespread floods, flash floods and landslides. Government disaster-risk summaries report more than 1,000 deaths in the event period. Because floods and landslides occurred simultaneously across many districts, totals differ by reporting boundary.','More than 1,000 in national summaries','Thousands reported/affected','Exceptional monsoon rainfall','Roads, bridges, homes, agricultural land and communication links were severely damaged.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal; UN disaster summaries',1,'PUBLISHED'),

('2008 Koshi Flood and Embankment Breach','2008-koshi-flood-embankment-breach',(SELECT id FROM categories WHERE slug='flood'),'2008-08-18','2008','Kusaha, Sunsari and Koshi Basin','The August 2008 Koshi embankment breach caused catastrophic flooding and large-scale displacement.','On 18 August 2008 the Koshi River breached its eastern embankment near Kusaha in Sunsari and shifted into an old channel. Floodwater inundated settlements and agricultural land in eastern Nepal and affected communities across the border in India. The event showed how river dynamics, embankment condition, sedimentation and exposure can combine into a transboundary disaster.','More than 200 across wider affected region; totals vary','Large numbers injured/displaced','Major river and embankment failure','Large areas of farmland and settlements were inundated and many households required prolonged assistance.','Government of Nepal; World Bank; ICIMOD; UN disaster assessments',1,'PUBLISHED'),

('2012 Seti River Flash Flood','2012-seti-river-flash-flood',(SELECT id FROM categories WHERE slug='flood'),'2012-05-05','2012','Seti River, Kaski and Pokhara area','A sudden destructive flood/debris-flow event on the Seti River caused major loss of life near Pokhara.','On 5 May 2012 a sudden surge of water and debris travelled down the Seti River near Pokhara. The event caused widespread destruction along the river corridor and killed many people. The sudden nature of the disaster highlighted the danger of high-mountain source processes and limited warning time in narrow valleys.','Dozens reported; exact totals vary','Reported injuries/missing','Sudden flash flood/debris flow','Settlements, bridges and riverbank infrastructure were damaged.','Government of Nepal disaster reports; ICIMOD and scientific studies',0,'PUBLISHED'),

('2014 Jure Landslide','2014-jure-landslide',(SELECT id FROM categories WHERE slug='landslide'),'2014-08-02','2014','Jure, Sindhupalchok','A massive landslide buried settlements, blocked the Sunkoshi River and formed a temporary lake.','On 2 August 2014 a massive slope failure occurred at Jure. ICIMOD reports about 6 million cubic metres of material entered the valley, forming a temporary lake of about 8 million cubic metres. The event killed 156 people and disrupted the Arniko Highway. Emergency teams worked to reduce the downstream outburst-flood threat.','156','Reported injuries; many displaced','Large rock/debris landslide','Settlements were buried, the Arniko Highway was disrupted and downstream communities faced flood risk.','ICIMOD; Government of Nepal; Department of Water Induced Disaster Management',1,'PUBLISHED'),

('2015 Earthquake-Triggered Landslides','2015-earthquake-triggered-landslides',(SELECT id FROM categories WHERE slug='landslide'),'2015-04-25','2015','Central and northern Nepal','The 2015 earthquake triggered thousands of landslides across the Himalayan and mid-hill regions.','The Mw 7.8 Gorkha earthquake destabilized slopes over a huge area. Landslides blocked roads, buried settlements, damaged trekking routes and isolated mountain communities. Major slope failures and rock avalanches occurred around Langtang. Monsoon rainfall later reactivated unstable slopes.','Included within overall earthquake toll; separate total varies','Included within overall earthquake totals','Earthquake-triggered slope failures','Roads, trails, villages and rivers were affected and some slopes remained unstable for years.','USGS; ICIMOD; Government of Nepal; peer-reviewed research',1,'PUBLISHED'),

('2017 Terai Monsoon Floods','2017-terai-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'2017-08-11','2017','Terai and southern Nepal','Exceptional monsoon rainfall in August 2017 caused widespread flooding across southern Nepal.','The 2017 monsoon brought intense rainfall to the Terai and other parts of Nepal. The World Bank estimated about 1.7 million people were affected and damages and losses were around US$585 million. Homes, farmland, roads, bridges, schools and health facilities were affected.','More than 140 reported in Nepal','Hundreds reported','Exceptional monsoon rainfall','Large areas of farmland and settlements were inundated and transport, health and education services were disrupted.','Government of Nepal Post Disaster Needs Assessment; World Bank; UN OCHA; DHM',1,'PUBLISHED'),

('2021 Melamchi Flood and Debris Flow','2021-melamchi-flood-debris-flow',(SELECT id FROM categories WHERE slug='flood'),'2021-06-15','2021','Melamchi and Helambu, Sindhupalchok','A catastrophic flood and debris-flow event struck the Melamchi and Helambu valleys.','On 15 June 2021 an extreme flood and debris-flow event struck Melamchi and Helambu. ICIMOD reported five deaths and 20 people missing in its immediate assessment. Homes, bridges, roads, hydropower facilities and the Melamchi Water Supply Project were damaged.','5 deaths; 20 missing in immediate ICIMOD assessment','Not consistently reported','Extreme flood/debris flow','Bridges, roads, homes, hydropower and water-supply infrastructure were damaged.','ICIMOD; Government of Nepal; NDRRMA',1,'PUBLISHED'),

('2021 October Floods and Landslides','2021-october-floods-landslides',(SELECT id FROM categories WHERE slug='flood'),'2021-10-18','2021','Multiple districts','Unusually heavy post-monsoon rainfall caused widespread floods and landslides in October 2021.','In October 2021 unusually heavy rainfall after the normal monsoon caused floods and landslides across many parts of Nepal. The timing made the event particularly disruptive. Government reporting recorded substantial deaths, infrastructure losses and agricultural damage, with totals varying by reporting cut-off.','Dozens reported; final total depends on reporting period','Many reported injuries','Extreme post-monsoon rainfall','Roads, bridges, homes, crops and services were damaged.','Government of Nepal/NDRRMA; DHM; UN situation reports',0,'PUBLISHED'),

('2024 Nepal Monsoon Floods and Landslides','2024-nepal-monsoon-floods-landslides',(SELECT id FROM categories WHERE slug='flood'),'2024-09-27','2024','Central and eastern Nepal including Kathmandu region','Extreme late-September rainfall caused severe floods and landslides across Nepal.','In late September 2024 exceptionally heavy rainfall caused severe flooding and landslides in multiple parts of Nepal. Kathmandu Valley and surrounding districts were among the hardest-hit areas. Roads, bridges, homes and public infrastructure suffered major damage. Final figures should follow the Government of Nepal’s consolidated assessment rather than early provisional media counts.','Official totals vary by assessment date','Hundreds reported in the wider disaster period','Extreme rainfall and river flooding','Homes, roads, bridges, agricultural land and public infrastructure were damaged.','Government of Nepal/NDRRMA; DHM; UN and World Bank assessments',0,'PUBLISHED'),

('1981 Zhangzangbo Glacial Lake Outburst Flood','1981-zhangzangbo-glof',(SELECT id FROM categories WHERE slug='glof'),'1981-07-11','1981','Zhangzangbo Valley and Sun Koshi River','The 1981 Zhangzangbo GLOF released an enormous volume of water and caused major damage along the Sun Koshi corridor.','On 11 July 1981 the Zhangzangbo/Cirenmaco GLOF released an estimated 19 million cubic metres of water in about one hour. ICIMOD reports five deaths in Nepal and hundreds injured. The flood destroyed the Friendship Bridge, damaged the Sun Koshi hydropower system and severely affected sections of the Arniko Highway.','5 reported in Nepal','Hundreds reported','GLOF; about 19 million m3 released in about one hour','Bridge, hydropower and highway infrastructure were severely damaged and trade and transport were disrupted.','ICIMOD; historical GLOF inventories; Nepal government technical reports',1,'PUBLISHED'),

('1985 Dig Tsho Glacial Lake Outburst Flood','1985-dig-tsho-glof',(SELECT id FROM categories WHERE slug='glof'),'1985-08-04','1985','Dig Tsho, Khumbu, Solukhumbu','The 1985 Dig Tsho GLOF destroyed a hydropower plant and infrastructure downstream.','On 4 August 1985 a GLOF from Dig Tsho sent a destructive surge down the Dudh Koshi system. ICIMOD records destruction of the nearly completed Namche hydropower plant, bridges, trails and cultivated land and loss of life.','Lives lost; exact total varies','Not consistently reported','GLOF','Namche hydropower, bridges, trails and agricultural land were damaged or destroyed.','ICIMOD GLOF inventories; Nepal government technical reports',1,'PUBLISHED'),

('1991 Chubung Glacial Lake Outburst Flood','1991-chubung-glof',(SELECT id FROM categories WHERE slug='glof'),'1991-01-01','1991','Khumbu/Rolwaling region','A Chubung GLOF is included in historical inventories of GLOFs affecting Nepal.','The 1991 Chubung event is documented in Himalayan GLOF inventories. The public record is less detailed than for the 1981 and 1985 events, so this article deliberately avoids unsupported precise casualty and damage numbers.','Not reliably established','Not reliably established','GLOF','Downstream channels and infrastructure were affected; detailed loss estimates are limited.','ICIMOD historical GLOF inventory',0,'PUBLISHED'),

('1998 Tam Pokhari Glacial Lake Outburst Flood','1998-tam-pokhari-glof',(SELECT id FROM categories WHERE slug='glof'),'1998-09-03','1998','Tam Pokhari, Inkhu Khola, Solukhumbu','An ice avalanche entered Tam Pokhari and triggered a destructive GLOF.','On 3 September 1998 an ice avalanche entered Tam Pokhari and generated a wave that breached the moraine dam. ICIMOD reports approximately NPR 156 million in damage and that lives were lost.','Some lives lost; exact total varies','Not consistently reported','GLOF triggered by ice avalanche','Downstream infrastructure and settlements were damaged.','ICIMOD; historical GLOF research',0,'PUBLISHED'),

('2017 Langmale Glacial Lake Outburst Flood','2017-langmale-glof',(SELECT id FROM categories WHERE slug='glof'),'2017-05-18','2017','Barun Valley, Makalu region','A GLOF affected the Barun Valley in eastern Nepal in 2017.','The Langmale GLOF occurred in the Barun Valley in 2017. It affected the high-mountain river system and demonstrated how changing glaciers and lakes can create sudden downstream hazards. Detailed event-level casualty and loss records are limited.','No confirmed major loss of life established in sources used','Not consistently reported','GLOF','High-mountain river channels and infrastructure were affected.','ICIMOD; Himalayan cryosphere and GLOF studies',0,'PUBLISHED'),

('2024 Thame Glacial Lake Outburst Flood','2024-thame-glof',(SELECT id FROM categories WHERE slug='glof'),'2024-08-16','2024','Thame, Solukhumbu','A GLOF swept through Thame after the breach of glacial lakes upstream.','On 16 August 2024 a GLOF struck Thame. ICIMOD initially identified Thyanbo glacial lake as the source; a later NDRRMA-ICIMOD investigation described successive breaching of Upper and Lower Ngole Cho lakes about 10 km upstream. The flood destroyed or damaged homes, a school, a health post, hotels, bridges and other infrastructure and displaced residents.','No major confirmed loss of life in initial ICIMOD assessment','Not consistently reported','Glacial lake outburst flood','Initial ICIMOD assessment documented 14 destroyed properties; later assessment reported widespread damage and displacement of 135 people.','ICIMOD; NDRRMA; DHM; ICIMOD 2025 Thame Valley GLOF study',1,'PUBLISHED'),

('2014 Annapurna Snowstorm and Avalanche Disaster','2014-annapurna-snowstorm',(SELECT id FROM categories WHERE slug='avalanche'),'2014-10-14','2014','Annapurna Circuit, Manang and Mustang','A severe October 2014 snowstorm and associated avalanches struck trekkers and mountain communities.','In October 2014 a severe snowstorm associated with Cyclone Hudhud produced heavy snow and blizzard conditions on the Annapurna Circuit. Trekkers and local people were caught in rapidly changing conditions, with avalanches and exposure contributing to deaths.','At least 43 reported','Many injured/rescued','Severe snowstorm and avalanche conditions','Trekkers died or required rescue; high passes and trails became dangerous.','Government of Nepal Ministry of Culture, Tourism and Civil Aviation; Himalayan rescue records; scientific studies',1,'PUBLISHED'),

('2019 Bara-Parsa Tornado','2019-bara-parsa-tornado',(SELECT id FROM categories WHERE slug='tornado'),'2019-03-31','2019','Bara and Parsa','A rare violent tornado struck southern Nepal on 31 March 2019.','A severe convective storm produced a destructive tornado in Bara and Parsa. Homes were damaged or destroyed and the event caused deaths and hundreds of injuries. The disaster demonstrated the need for severe-weather observation, public warnings and safer construction in the Terai.','29','Hundreds','Tornado/severe rotating convective storm','Homes, roofs, electricity and local infrastructure were heavily damaged.','Government of Nepal disaster assessment; DHM; NDRRMA; meteorological studies',1,'PUBLISHED'),

('2016 Nepal Wildfire Season','2016-nepal-wildfire-season',(SELECT id FROM categories WHERE slug='wildfire'),'2016-04-01','2016','Multiple districts across Nepal','The 2016 dry-season wildfire period was a notable wildfire season affecting forests, air quality and communities.','Nepal experiences recurring dry-season forest fires before the summer monsoon. The 2016 season affected forests in numerous districts. Fire danger is influenced by dry vegetation, rainfall deficits, wind and human ignition. Satellite fire monitoring has become an important part of national wildfire observation.','Varies by incident','Varies by incident','Widespread dry-season wildfire activity','Forest ecosystems, air quality, biodiversity, agricultural land and nearby settlements were affected.','Department of Forests and Soil Conservation; ICIMOD; NASA FIRMS',0,'PUBLISHED'),

('2021 Nepal Wildfire Season','2021-nepal-wildfire-season',(SELECT id FROM categories WHERE slug='wildfire'),'2021-03-01','2021','Multiple districts across Nepal','Nepal experienced widespread wildfire activity in the dry season of 2021, with extensive smoke and air-quality impacts.','The dry season of 2021 produced widespread wildfire activity across Nepal. Satellite monitoring showed extensive fire activity and smoke affected populated areas during periods of poor atmospheric dispersion. The season illustrates how dry conditions, vegetation, wind and human ignition can combine into national-scale wildfire and air-quality problems.','Multiple deaths reported across incidents; no single wildfire toll','Multiple injuries reported across incidents','Widespread wildfire activity','Forests and biodiversity were damaged and smoke affected air quality over broad areas.','ICIMOD; NASA FIRMS; Government of Nepal forest and disaster reports',0,'PUBLISHED'),

('Major Nepal Lightning Hazard','major-nepal-lightning-hazard',(SELECT id FROM categories WHERE slug='lightning'),'2019-04-01','Recent decades','Terai, hills and mountain districts','Lightning is a recurring high-fatality hazard in Nepal, especially during pre-monsoon and monsoon seasons.','Lightning strikes frequently occur during Nepal’s convective storm seasons. People working in agriculture, walking outdoors or sheltering under isolated trees are particularly vulnerable. Government disaster statistics show repeated deaths and injuries across Nepal. This article is a hazard-history entry; individual incidents should be added as separate records when available.','Annual totals vary; use government incident records','Annual totals vary','Severe convective thunderstorms','Deaths, injuries, livestock losses, fires and electrical damage occur every year.','Department of Hydrology and Meteorology; Nepal Disaster Risk Reduction Portal; Ministry of Home Affairs statistics',1,'PUBLISHED'),

('Major Nepal Hailstorm and Windstorm Hazard','major-nepal-hailstorm-windstorm-hazard',(SELECT id FROM categories WHERE slug='storm'),'2019-01-01','Recent decades','Terai, hills and mountain districts','Hailstorms, damaging winds and severe thunderstorms are recurring hazards across Nepal.','Severe thunderstorms can produce hail, strong winds, lightning and intense short-duration rainfall. These events damage crops, roofs, greenhouses, electricity infrastructure and communications. Agriculture is especially vulnerable because a localized hailstorm can destroy seasonal crops rapidly.','Varies by event','Varies by event','Severe thunderstorm, hail and wind','Agriculture, roofs, power lines and local infrastructure can be damaged.','Department of Hydrology and Meteorology; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('Nepal Drought and Dry-Season Risk','nepal-drought-history-and-risk',(SELECT id FROM categories WHERE slug='drought'),'2009-01-01','2008-2009','Western, mid-western and far-western Nepal','Drought often develops gradually through deficient winter or monsoon rainfall and produces agricultural and water-security impacts.','Drought develops over weeks or months rather than as a single sudden event. Nepal has experienced recurring agricultural drought, particularly when winter or monsoon rainfall is deficient. Western and mid-western farming communities can be especially vulnerable. Impacts include reduced crop yields, livestock stress, drinking-water shortages and food-security pressure.','No single disaster death toll','Livelihood and food-security impacts','Seasonal rainfall deficit','Agriculture, livestock, drinking water and rural livelihoods can be affected.','DHM; Ministry of Agriculture and Livestock Development; FAO; Government of Nepal assessments',0,'PUBLISHED'),

('Nepal Terai Heat Wave Hazard','nepal-terai-heat-wave-hazard',(SELECT id FROM categories WHERE slug='heat-wave'),'2024-05-01','Recent decades','Terai and southern plains','Extreme heat is an important and increasingly concerning hazard in Nepal’s Terai.','The Terai regularly experiences very high temperatures during late spring and early summer. Heat risk is increased by humidity, urbanization, limited shade, outdoor work and inadequate access to cooling and drinking water. Heat waves are not always recorded as discrete disasters with reliable national mortality figures, so individual episodes should be linked to official weather and health records.','Event-specific mortality varies','Heat-related illness varies','Extreme high temperature','Health, labor productivity, agriculture, livestock and water demand can be affected.','DHM; Ministry of Health and Population; WHO heat-health guidance',0,'PUBLISHED'),

('Nepal Terai Cold Wave Hazard','nepal-terai-cold-wave-hazard',(SELECT id FROM categories WHERE slug='cold-wave'),'2019-01-01','Recent decades','Terai and southern plains','Cold waves, dense fog and prolonged winter chill periodically affect Nepal’s Terai.','Winter cold waves are recurring hazards in southern Nepal. Dense fog and low temperatures affect transport, schools, agriculture and vulnerable people. Impacts are often greatest among people without adequate heating and among older adults and children.','Event-specific mortality varies','Cold-related illness varies','Low temperature and persistent fog','Health, transport, agriculture and livestock can be affected.','DHM; Government of Nepal winter disaster reports',0,'PUBLISHED'),

('2020 Nepal Monsoon Floods and Landslides','2020-nepal-monsoon-floods-landslides',(SELECT id FROM categories WHERE slug='flood'),'2020-07-01','2020','Multiple districts','The 2020 monsoon produced widespread floods and landslides across Nepal.','During the 2020 monsoon heavy rainfall triggered floods and landslides across numerous districts. Mountain roads were repeatedly blocked, houses were damaged and agricultural land was affected. The disaster occurred during the COVID-19 pandemic, complicating evacuation and relief.','Season total varies by reporting cut-off','Many reported','Monsoon flood and rainfall-triggered landslides','Roads, bridges, homes, farms and local infrastructure were damaged.','Government of Nepal/NDRRMA; DHM; UN situation reports',0,'PUBLISHED'),

('2022 Nepal Monsoon Floods and Landslides','2022-nepal-monsoon-floods-landslides',(SELECT id FROM categories WHERE slug='flood'),'2022-06-01','2022','Multiple districts','The 2022 monsoon produced repeated floods and landslides across Nepal.','Monsoon rainfall in 2022 triggered repeated floods, landslides and road disruptions. Impacts included deaths, damaged homes, blocked highways, crop losses and disruption to local services. The season consisted of many separate incidents rather than one single disaster.','Season total varies by official reporting period','Many reported','Monsoon rainfall','Transport, agriculture, housing and local infrastructure were repeatedly affected.','Government of Nepal/NDRRMA; DHM',0,'PUBLISHED'),

('2023 Nepal Monsoon Floods and Landslides','2023-nepal-monsoon-floods-landslides',(SELECT id FROM categories WHERE slug='flood'),'2023-06-01','2023','Multiple districts','Floods and landslides during the 2023 monsoon caused repeated casualties and infrastructure damage.','The 2023 monsoon produced numerous localized floods, landslides and debris flows. Mountain highways and rural roads were particularly vulnerable to slope failure, while river flooding affected settlements and agricultural land. Individual incident records are more useful than one national event total.','Season total varies by official reporting period','Many reported','Monsoon rainfall','Roads, bridges, homes, farms and river corridors were affected.','Government of Nepal/NDRRMA; DHM',0,'PUBLISHED'),

('2025 Nepal Monsoon Flood and Landslide Events','2025-nepal-monsoon-flood-landslide-events',(SELECT id FROM categories WHERE slug='flood'),'2025-06-01','2025','Multiple districts','Nepal continued to experience recurring monsoon floods, landslides and debris flows in 2025.','The 2025 monsoon produced multiple localized flood and landslide disasters affecting highways, bridges, settlements, agriculture and hydropower infrastructure. Because the season consisted of many incidents, final casualty and damage totals should be taken from the consolidated Government of Nepal database.','Season total varies by official reporting period','Many reported','Monsoon rainfall','Transport, settlements, agriculture and infrastructure were repeatedly disrupted.','Government of Nepal/NDRRMA; DHM',0,'PUBLISHED'),

('2026 Rasuwa High-Mountain Flash Flood Disaster','2026-rasuwa-high-mountain-flash-flood',(SELECT id FROM categories WHERE slug='flood'),'2026-08-26','2026','Rasuwa and northern Nepal','A major high-mountain flash flood struck Rasuwa in August 2026, highlighting cryosphere-linked flood and debris-flow risk.','On 26 August 2026 a major flash flood swept through Rasuwa district in northern Nepal. The event affected settlements and infrastructure along the mountain river corridor and raised concerns about downstream flooding. Because the disaster is recent, casualty and damage assessments can change as search-and-rescue operations and official investigations continue.','Ongoing assessment; final total not established','Ongoing assessment','High-mountain flash flood/debris-flow event','Roads, bridges, settlements and border-area infrastructure were affected; downstream risk required monitoring.','ICIMOD 26 August 2026 media advisory; Government of Nepal/NDRRMA; DHM',1,'PUBLISHED'),

('1987 Eastern Nepal Earthquake','1987-eastern-nepal-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1987-01-01','1987','Eastern Nepal','A damaging earthquake affected eastern Nepal and is included in national historical earthquake records.','The 1987 event affected communities in eastern Nepal, where rural masonry and unreinforced buildings were vulnerable to shaking. Historical summaries provide limited event-level detail, so this record is intentionally cautious about casualties and magnitude.','Not reliably established','Not reliably established','Historical earthquake; magnitude varies by catalogue','Local buildings and infrastructure were damaged in affected districts.','NSET historical earthquake catalogue; Government of Nepal records',0,'PUBLISHED'),
('1994 Nepal Earthquake Sequence','1994-nepal-earthquake-sequence',(SELECT id FROM categories WHERE slug='earthquake'),'1994-01-01','1994','Central and western Nepal','A sequence of earthquakes in 1994 caused localized damage and renewed concern about Himalayan seismic risk.','Several moderate earthquakes were recorded in Nepal during 1994. The available public summaries do not support one definitive national casualty or damage total. Earthquake sequences can produce repeated shaking and increase the vulnerability of already damaged buildings.','Not reliably established','Not reliably established','Moderate earthquake sequence','Localized structural damage and disruption were reported in affected communities.','NSET earthquake catalogue; USGS earthquake records',0,'PUBLISHED'),
('1997 Bajura Earthquake','1997-bajura-earthquake',(SELECT id FROM categories WHERE slug='earthquake'),'1997-01-01','1997','Bajura and far-western Nepal','A historical earthquake affected remote communities in far-western Nepal.','The 1997 Bajura event is recorded in historical earthquake listings for Nepal. Remoteness, difficult terrain and limited reporting capacity made contemporaneous damage assessment difficult. This entry should be expanded with district-level government records where available.','Not reliably established','Not reliably established','Magnitude not consistently reported','Rural homes, roads and local services may have been affected.','NSET earthquake catalogue; district administration records',0,'PUBLISHED'),
('2001 Nepal Himalayan Earthquake Activity','2001-nepal-himalayan-earthquake-activity',(SELECT id FROM categories WHERE slug='earthquake'),'2001-01-01','2001','Nepal Himalaya','Earthquake activity in 2001 included moderate events felt across parts of Nepal.','Nepal lies along an active collision zone and experiences frequent earthquakes below the threshold of major disaster. The 2001 record illustrates the importance of maintaining monitoring and preparedness even when an individual event causes limited damage.','Not reliably established','Not reliably established','Moderate regional seismicity','Limited local effects were reported in available summaries.','NSET earthquake catalogue; USGS earthquake records',0,'PUBLISHED'),
('2005 Nepal Earthquake Events','2005-nepal-earthquake-events',(SELECT id FROM categories WHERE slug='earthquake'),'2005-01-01','2005','Nepal and Himalayan region','Moderate earthquakes in 2005 were felt in parts of Nepal and contributed to the long record of Himalayan seismic activity.','The 2005 events are best understood as a group of moderate earthquakes rather than one single national disaster. Public records do not provide a consistent consolidated loss total, but the events reinforce the need for resilient construction and local preparedness.','Not reliably established','Not reliably established','Moderate Himalayan earthquakes','Localized shaking and minor damage were possible in affected areas.','NSET earthquake catalogue; USGS',0,'PUBLISHED'),
('2007 Nepal Earthquake Events','2007-nepal-earthquake-events',(SELECT id FROM categories WHERE slug='earthquake'),'2007-01-01','2007','Nepal Himalaya','Nepal recorded several moderate seismic events in 2007, with effects varying by location and building vulnerability.','The 2007 earthquake record includes felt events across the Himalayan region. Because many records combine felt reports with instrument observations, casualty and damage figures should be taken from individual event reports rather than inferred from the year alone.','Not reliably established','Not reliably established','Moderate seismic events','Localized shaking and minor structural effects were reported in some areas.','NSET earthquake catalogue; USGS earthquake records',0,'PUBLISHED'),
('2010 Nepal Earthquake Events','2010-nepal-earthquake-events',(SELECT id FROM categories WHERE slug='earthquake'),'2010-01-01','2010','Nepal and adjoining Himalayan region','Moderate seismic events in 2010 affected parts of Nepal without a single consolidated national disaster toll.','The 2010 record shows how frequent smaller earthquakes form part of the background hazard in Nepal. Stronger local effects depend on depth, distance, soil conditions and construction quality.','Not reliably established','Not reliably established','Moderate Himalayan seismicity','Localized shaking was reported; no single nationwide damage estimate is used here.','NSET earthquake catalogue; USGS earthquake records',0,'PUBLISHED'),
('2014 Nepal Earthquake Events','2014-nepal-earthquake-events',(SELECT id FROM categories WHERE slug='earthquake'),'2014-01-01','2014','Nepal Himalaya','Moderate earthquakes recorded before the 2015 disaster affected communities and provided another reminder of regional seismic exposure.','Nepal experienced multiple felt earthquakes in 2014. The available summaries do not support treating them as one event or assigning a combined casualty figure. They are included as a historical activity record for researchers reviewing the lead-up to 2015.','Not reliably established','Not reliably established','Moderate regional earthquakes','Localized shaking and minor damage were reported in some locations.','NSET earthquake catalogue; USGS',0,'PUBLISHED'),

('1984 Narayani Flood','1984-narayani-flood',(SELECT id FROM categories WHERE slug='flood'),'1984-07-01','1984','Narayani Basin','A major monsoon flood affected communities and farmland in the Narayani basin.','The Narayani system carries water from the high Himalaya through the hills and plains. The 1984 flood is included in national historical flood records, although older summaries do not consistently report district-level casualties and losses.','Historical totals vary','Not consistently documented','Severe monsoon flood','River settlements, farmland, roads and bridges were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('1986 West Rapti Flood','1986-west-rapti-flood',(SELECT id FROM categories WHERE slug='flood'),'1986-07-01','1986','West Rapti Basin','The West Rapti basin experienced a damaging historical monsoon flood in 1986.','The West Rapti is vulnerable to rapid rises after intense rainfall in its hill catchments. The 1986 flood is listed in historical disaster records, while precise event-level loss figures require verification from archival district reports.','Historical totals vary','Not consistently documented','Severe monsoon flood','Homes, crops, roads and river crossings were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('1989 Karnali Flood','1989-karnali-flood',(SELECT id FROM categories WHERE slug='flood'),'1989-07-01','1989','Karnali Basin','A major flood in the Karnali basin affected river communities and transport links.','Flood risk in the Karnali combines intense monsoon rain, steep tributaries, sediment movement and exposed settlements. The 1989 event is retained as a historical basin record without unsupported precise casualty claims.','Historical totals vary','Not consistently documented','Severe monsoon flood','Riverbank settlements, farmland, roads and bridges were affected.','Government of Nepal disaster-risk profile; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('1998 Nepal Monsoon Floods','1998-nepal-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'1998-07-01','1998','Multiple districts','The 1998 monsoon produced floods and landslides in several parts of Nepal.','Seasonal disaster summaries identify 1998 as a year of damaging monsoon flooding. Since the season consisted of many separate incidents, a single national story can hide important district differences and should be supplemented with local records.','Season total varies by source','Many reported','Heavy monsoon rainfall','Homes, crops, roads, bridges and river corridors were affected.','Government of Nepal disaster-risk profile; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2002 Nepal Monsoon Floods','2002-nepal-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'2002-07-01','2002','Multiple districts','Flooding during the 2002 monsoon damaged settlements, farms and transport infrastructure.','Repeated monsoon rainfall caused river flooding and localized flash floods across Nepal in 2002. The available public summaries are stronger on affected districts than on a single consolidated casualty total.','Season total varies by source','Many reported','Monsoon flood and flash flood','Agricultural land, homes, roads and bridges were damaged.','Government of Nepal disaster-risk profile; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2004 Nepal Monsoon Floods','2004-nepal-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'2004-07-01','2004','Terai and hill districts','The 2004 monsoon caused repeated river floods and local flash floods across Nepal.','Monsoon flooding in 2004 affected lowland river corridors and hill valleys. This record groups the season for archive navigation; individual district events should be cited separately when precise figures are required.','Season total varies by source','Many reported','Heavy monsoon rainfall','Homes, fields, roads and local services were affected.','Government of Nepal disaster-risk profile; DHM',0,'PUBLISHED'),
('2006 Nepal Monsoon Floods','2006-nepal-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'2006-07-01','2006','Multiple districts','Heavy monsoon rainfall in 2006 caused flooding and landslides across several regions of Nepal.','The 2006 season demonstrates the compound nature of monsoon disasters: river flooding in the plains occurred alongside landslides and road blockages in the hills. National totals vary with the reporting period used.','Season total varies by source','Many reported','Monsoon flood and rainfall-triggered landslides','Transport, homes, farmland and public infrastructure were affected.','Government of Nepal disaster-risk profile; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2010 Nepal Monsoon Floods','2010-nepal-monsoon-floods',(SELECT id FROM categories WHERE slug='flood'),'2010-07-01','2010','Multiple districts','The 2010 monsoon brought repeated flooding and landslides to Nepal.','Seasonal rainfall caused river flooding, flash floods and slope failures in multiple districts. The impacts were distributed across many local events, so consolidated figures should be checked against official annual disaster reports.','Season total varies by source','Many reported','Monsoon rainfall','Roads, bridges, homes, crops and local utilities were damaged.','Government of Nepal disaster-risk profile; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),

('1985 Baglung Landslide','1985-baglung-landslide',(SELECT id FROM categories WHERE slug='landslide'),'1985-07-01','1985','Baglung and western hills','A monsoon-triggered landslide affected settlements and transport routes in the western hills.','The steep slopes of western Nepal are vulnerable to landslides when prolonged rainfall saturates soil and weathered rock. The 1985 Baglung event is included in historical landslide records, while detailed casualty figures should be taken from district archives.','Historical totals vary','Not consistently documented','Rainfall-triggered landslide','Homes, farmland, trails and roads were affected.','Government of Nepal disaster-risk profile; Department of Water Induced Disaster Management',0,'PUBLISHED'),
('1988 Western Nepal Landslides','1988-western-nepal-landslides',(SELECT id FROM categories WHERE slug='landslide'),'1988-07-01','1988','Western and mid-western Nepal','Heavy monsoon rain triggered landslides across vulnerable western hill districts in 1988.','This seasonal record groups multiple slope failures rather than presenting them as one single slide. Terrain, road cutting, deforestation and rainfall can interact to increase landslide risk.','Season total varies by source','Many reported or displaced','Monsoon-triggered slope failures','Roads, homes, farms and mountain trails were damaged or blocked.','Government of Nepal disaster-risk profile; NDRRMA; Department of Water Induced Disaster Management',0,'PUBLISHED'),
('1996 Sindhupalchok Landslide Events','1996-sindhupalchok-landslide-events',(SELECT id FROM categories WHERE slug='landslide'),'1996-07-01','1996','Sindhupalchok and central hills','A series of rainfall-triggered landslides affected Sindhupalchok and nearby hill districts.','Sindhupalchok has steep terrain, active river incision and settlements along transport corridors. Historical monsoon records identify repeated landslide impacts in the area, although a single consolidated casualty count is not available for this grouped entry.','Season total varies by source','Not consistently documented','Rainfall-triggered landslides','Roads, homes, trails and river channels were affected.','Government of Nepal disaster-risk profile; Department of Water Induced Disaster Management; ICIMOD',0,'PUBLISHED'),
('2002 Myagdi Landslide Events','2002-myagdi-landslide-events',(SELECT id FROM categories WHERE slug='landslide'),'2002-07-01','2002','Myagdi and western hills','Monsoon landslides in Myagdi affected rural settlements and mountain transport routes.','The 2002 monsoon produced repeated slope failures in western hill districts including Myagdi. Landslide impacts are often cumulative, with roads blocked repeatedly and communities isolated for days or weeks.','Season total varies by source','Not consistently documented','Rainfall-triggered landslides','Rural roads, homes, fields and trails were affected.','Government of Nepal disaster-risk profile; NDRRMA; Department of Water Induced Disaster Management',0,'PUBLISHED'),
('2018 Sunkoshi Landslide Events','2018-sunkoshi-landslide-events',(SELECT id FROM categories WHERE slug='landslide'),'2018-07-01','2018','Sindhupalchok and Sunkoshi corridor','Rainfall-triggered landslides repeatedly affected the Sunkoshi transport corridor in 2018.','The Sunkoshi corridor combines steep slopes, active rivers and major road infrastructure. Landslides during the 2018 monsoon blocked transport and raised concerns about secondary river blockage and debris-flow hazards.','Season total varies by incident','Not consistently documented','Monsoon-triggered landslides','Highways, settlements, river channels and local commerce were disrupted.','Department of Roads; NDRRMA; Department of Water Induced Disaster Management',0,'PUBLISHED'),
('2020 Sindhupalchok Landslides','2020-sindhupalchok-landslides',(SELECT id FROM categories WHERE slug='landslide'),'2020-07-09','2020','Sindhupalchok','Severe rainfall-triggered landslides in Sindhupalchok caused deaths, displacement and major infrastructure damage.','During the 2020 monsoon, destructive landslides affected Sindhupalchok and nearby valleys. Several communities experienced loss of homes and road access. The event occurred in a region already exposed to earthquake-related slope instability and difficult terrain.','Multiple deaths reported; event totals vary','Many displaced or injured','Extreme rainfall and slope failure','Homes, roads, bridges and local services were damaged or isolated.','Government of Nepal/NDRRMA; DHM; ICIMOD',1,'PUBLISHED'),

('1979 Annapurna Avalanche Events','1979-annapurna-avalanche-events',(SELECT id FROM categories WHERE slug='avalanche'),'1979-01-01','1979','Annapurna and high mountain districts','Avalanches in the Annapurna region affected mountaineering routes and high-altitude communities.','High mountain avalanche records are incomplete for earlier decades, but the Annapurna region has long experienced avalanche danger from heavy snow, wind loading and unstable slopes. This grouped entry should be supplemented by expedition and local records.','Not reliably established','Not reliably established','High-altitude avalanche hazard','Expedition routes, grazing areas and mountain trails were affected.','Department of Tourism; Himalayan Database; historical expedition records',0,'PUBLISHED'),
('1989 Everest Avalanche Events','1989-everest-avalanche-events',(SELECT id FROM categories WHERE slug='avalanche'),'1989-01-01','1989','Khumbu and Mount Everest region','Avalanche activity in the Everest region has repeatedly threatened climbers, porters and local communities.','The Everest region contains steep hanging glaciers, snow-loaded slopes and narrow travel corridors. Historical avalanche events before the modern reporting era are not always documented with consistent casualty figures, so this entry emphasizes the hazard context.','Not reliably established','Not reliably established','High-altitude avalanche hazard','Climbing routes, trails, camps and mountain livelihoods were exposed.','Himalayan Database; Department of Tourism; expedition safety records',0,'PUBLISHED'),
('2009 Annapurna Avalanche Events','2009-annapurna-avalanche-events',(SELECT id FROM categories WHERE slug='avalanche'),'2009-01-01','2009','Annapurna and Mustang','Snowfall and avalanche conditions affected mountain routes in the Annapurna region in 2009.','Heavy snow, wind and rapid weather changes can create avalanche conditions on the Annapurna Circuit and adjoining valleys. Earlier event-level records are uneven, so this article should be treated as a regional hazard-history record rather than a single precisely measured disaster.','Not reliably established','Not reliably established','Snowstorm and avalanche conditions','Trails and high passes were closed or made hazardous; rescue access was difficult.','Department of Tourism; Himalayan Database; local administration records',0,'PUBLISHED'),
('2022 Manaslu Avalanche','2022-manaslu-avalanche',(SELECT id FROM categories WHERE slug='avalanche'),'2022-09-26','2022','Manaslu, Gorkha','An avalanche on Manaslu affected climbers during the autumn expedition season.','In September 2022 an avalanche struck the Manaslu climbing area during a period of active expeditions. High-altitude avalanches can be triggered by snowfall, wind loading, serac collapse and changing temperatures. Casualty and rescue numbers should be checked against official expedition reports.','Reported deaths; final total varies by source','Reported injuries','High-altitude avalanche','Camps, climbing routes and expedition operations were affected.','Department of Tourism; Himalayan Database; expedition safety reports',0,'PUBLISHED'),

('1977 Nepal Glacial Lake Flood Risk','1977-nepal-glacial-lake-flood-risk',(SELECT id FROM categories WHERE slug='glof'),'1977-01-01','1977','Nepal Himalaya','Early inventories documented growing glacial lakes and potential outburst-flood hazards in Nepal.','Before detailed satellite monitoring, field teams documented glacial lakes and downstream exposure through surveys and local reports. This record represents the emergence of systematic GLOF risk awareness rather than one confirmed single-lake disaster.','Not applicable to a single event','Not applicable','Glacial lake outburst flood risk','Downstream valleys, bridges, trails and hydropower sites were exposed.','ICIMOD historical cryosphere research; Nepal technical reports',0,'PUBLISHED'),
('1980 Nepal Himalayan GLOF Events','1980-nepal-himalayan-glof-events',(SELECT id FROM categories WHERE slug='glof'),'1980-01-01','1980','Nepal Himalaya','Historical inventories identify destructive glacial lake outburst flood activity in the Nepal Himalaya around the early 1980s.','GLOFs can release water, ice and sediment with very little warning. Early event inventories are sometimes inconsistent in dates and names, so this grouped record avoids attributing uncertain details to a specific lake without a technical source.','Event totals vary by inventory','Event totals vary by inventory','Glacial lake outburst flood','River channels, settlements, trails and infrastructure can be damaged downstream.','ICIMOD GLOF inventory; Nepal government technical reports',0,'PUBLISHED'),
('1994 Nepal GLOF Inventory Events','1994-nepal-glof-inventory-events',(SELECT id FROM categories WHERE slug='glof'),'1994-01-01','1994','Nepal Himalaya','GLOF inventories from the 1990s documented increasing concern about rapidly changing Himalayan lakes.','The 1990s saw more systematic attention to glacial lakes, remote sensing and downstream exposure. Some inventory entries describe past events while others describe risk rather than confirmed outburst floods; researchers should distinguish the two when expanding this record.','Not reliably established','Not reliably established','GLOF risk and historical events','Downstream settlements and infrastructure were assessed for potential flood exposure.','ICIMOD; Department of Hydrology and Meteorology; Nepal technical studies',0,'PUBLISHED'),
('2007 Nepal GLOF Monitoring Period','2007-nepal-glof-monitoring-period',(SELECT id FROM categories WHERE slug='glof'),'2007-01-01','2007','Nepal Himalaya','Monitoring programs in the 2000s tracked expanding glacial lakes and potential outburst-flood hazards.','Remote sensing, field surveys and community observations improved knowledge of Nepal glacial lakes during the 2000s. This entry records a period of risk monitoring rather than a single flood, and it highlights why lake conditions and downstream warning systems require continuing updates.','Not applicable to a single event','Not applicable','Glacial lake growth and outburst risk','Potential exposure included hydropower, bridges, trails and settlements downstream.','ICIMOD; DHM; Nepal glacial lake inventories',0,'PUBLISHED'),

('2007 Nepal Lightning Incidents','2007-nepal-lightning-incidents',(SELECT id FROM categories WHERE slug='lightning'),'2007-04-01','2007','Terai and hill districts','Lightning caused recurring deaths, injuries and livestock losses during Nepal thunderstorms in 2007.','Lightning risk increases during pre-monsoon storms and remains high where people work outdoors or shelter under isolated trees and simple structures. Annual reporting groups many local incidents, so this entry should be paired with district-level records.','Annual total varies by government record','Annual total varies','Severe convective thunderstorms','People, livestock, homes and electrical systems were affected by strikes and related fires.','Ministry of Home Affairs disaster statistics; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2012 Nepal Lightning Incidents','2012-nepal-lightning-incidents',(SELECT id FROM categories WHERE slug='lightning'),'2012-04-01','2012','Terai, hills and mountain districts','Lightning remained a recurring deadly hazard across Nepal during the 2012 storm seasons.','The 2012 record illustrates that lightning disasters are distributed across many small incidents. Better public warnings, grounded shelters, safer school procedures and avoidance of open fields can reduce exposure.','Annual total varies by government record','Annual total varies','Severe convective thunderstorms','Deaths, injuries, livestock loss and structure fires were reported in separate incidents.','Ministry of Home Affairs disaster statistics; DHM',0,'PUBLISHED'),
('2016 Nepal Lightning Incidents','2016-nepal-lightning-incidents',(SELECT id FROM categories WHERE slug='lightning'),'2016-04-01','2016','Terai and hill districts','Thunderstorm lightning caused repeated casualties and damage in Nepal during 2016.','Lightning incidents often rise during the transition into the monsoon. The hazard is difficult to localize without timely weather alerts, and household or workplace decisions made during a storm strongly influence outcomes.','Annual total varies by government record','Annual total varies','Severe convective thunderstorms','People, livestock, roofs, electrical equipment and communications were affected.','DHM; Ministry of Home Affairs disaster statistics; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2024 Nepal Lightning Incidents','2024-nepal-lightning-incidents',(SELECT id FROM categories WHERE slug='lightning'),'2024-04-01','2024','Multiple districts','Lightning continued to produce recurring deaths and injuries across Nepal in 2024.','The 2024 season included multiple lightning incidents during severe convective weather. Final annual counts should be taken from consolidated government data because early media reports can omit remote districts or later deaths.','Final annual total varies by reporting cut-off','Many reported','Severe convective thunderstorms','Communities, homes, farms, livestock and electrical systems were affected.','DHM; NDRRMA; Ministry of Home Affairs disaster statistics',0,'PUBLISHED'),

('1990 Nepal Hailstorm Season','1990-nepal-hailstorm-season',(SELECT id FROM categories WHERE slug='storm'),'1990-03-01','1990','Hills and Terai','Hailstorms and severe winds damaged crops and roofs in several parts of Nepal during the 1990 storm season.','Localized hailstorms can create large agricultural losses even when the affected area is small. Historical national reporting is incomplete for the 1990 season, so this entry focuses on the recurring hazard pattern rather than a single national loss figure.','Not reliably established','Not reliably established','Hail and severe convective wind','Crops, roofs, livestock shelters and local utilities were exposed.','DHM historical weather records; Government of Nepal disaster reports',0,'PUBLISHED'),
('2000 Nepal Severe Windstorms','2000-nepal-severe-windstorms',(SELECT id FROM categories WHERE slug='storm'),'2000-04-01','2000','Terai and hill districts','Severe windstorms and thunderstorms affected settlements and agriculture in Nepal around 2000.','Strong convective winds can occur before or during the monsoon and may damage roofs, trees, power lines and standing crops. The available historical summaries group incidents by district and do not provide one reliable national casualty total.','Incident totals vary','Incident totals vary','Severe convective windstorm','Roofs, trees, power lines and crops were damaged.','DHM; Nepal Disaster Risk Reduction Portal; district disaster records',0,'PUBLISHED'),
('2008 Nepal Hailstorm Events','2008-nepal-hailstorm-events',(SELECT id FROM categories WHERE slug='storm'),'2008-04-01','2008','Multiple districts','Hailstorms during the 2008 pre-monsoon period affected crops, homes and local infrastructure.','Hail is a short-duration but high-impact hazard for farming communities. The 2008 incidents are grouped for archive discovery because individual district records are more precise than a single nationwide total.','Incident totals vary','Incident totals vary','Severe hailstorm','Crops, greenhouses, roofs and livestock shelters were damaged.','DHM; Ministry of Agriculture and Livestock Development; local administration records',0,'PUBLISHED'),
('2023 Nepal Severe Storms','2023-nepal-severe-storms',(SELECT id FROM categories WHERE slug='storm'),'2023-04-01','2023','Multiple districts','Severe thunderstorms, damaging winds and hail affected Nepal during the 2023 storm seasons.','Storm cells can produce several hazards at once: lightning, hail, wind damage and intense short-duration rain. The 2023 record groups recurring events and should be read alongside individual incident reports and crop-loss assessments.','Incident totals vary','Incident totals vary','Severe thunderstorm and hail','Agriculture, roofs, electricity and communications were affected.','DHM; NDRRMA; Ministry of Agriculture and Livestock Development',0,'PUBLISHED'),

('2000 Nepal Tornado-Like Wind Events','2000-nepal-tornado-like-wind-events',(SELECT id FROM categories WHERE slug='tornado'),'2000-01-01','2000','Terai plains','Tornado-like rotating wind events are rare in Nepal but can cause concentrated destruction when they occur.','Before the 2019 Bara event, many severe local windstorms were reported without the observations needed to classify them confidently as tornadoes. This record preserves the hazard history while avoiding an unsupported event count or casualty figure.','Not reliably established','Not reliably established','Tornado-like severe wind; classification uncertain','Roofs, trees, crops and power infrastructure can be damaged along a narrow track.','DHM historical weather records; local administration reports',0,'PUBLISHED'),
('2014 Nepal Severe Rotating Windstorm Reports','2014-nepal-severe-rotating-windstorm-reports',(SELECT id FROM categories WHERE slug='tornado'),'2014-01-01','2014','Southern Nepal','Severe rotating windstorm reports in southern Nepal predated improved public attention to the country tornado hazard.','Local storm reports do not always include radar or damage-path surveys, making tornado classification difficult. This record is retained as a research lead and should be updated only with verified meteorological evidence.','Not reliably established','Not reliably established','Severe rotating windstorm; classification uncertain','Concentrated roof, crop and tree damage was reported in local storm accounts.','DHM; district administration records; meteorological research',0,'PUBLISHED'),
('2022 Nepal Tornado-Like Storm Reports','2022-nepal-tornado-like-storm-reports',(SELECT id FROM categories WHERE slug='tornado'),'2022-01-01','2022','Terai and southern plains','Localized destructive windstorms in the Terai continued to show the need for better severe-weather observation.','Nepal has limited long-term tornado observations, so reports of rotating winds should be verified with damage surveys, radar and eyewitness evidence. This entry groups possible events rather than asserting that every report was a confirmed tornado.','Not reliably established','Not reliably established','Tornado-like severe wind; classification uncertain','Homes, roofs, crops and local utilities were exposed.','DHM; NDRRMA; meteorological research',0,'PUBLISHED'),

('1992 Nepal Drought Conditions','1992-nepal-drought-conditions',(SELECT id FROM categories WHERE slug='drought'),'1992-01-01','1992','Western and mid-western Nepal','Rainfall deficits contributed to agricultural and water stress in parts of Nepal during the early 1990s.','Drought conditions are measured against local rainfall, soil moisture, water supply and crop needs. The 1992 record is best treated as a seasonal drought reference because national loss estimates and district severity classifications vary.','No single disaster death toll','Livelihood and food-security impacts','Seasonal rainfall deficit','Crops, livestock, drinking water and household income were affected.','DHM; FAO; Ministry of Agriculture and Livestock Development',0,'PUBLISHED'),
('2006 Nepal Drought Conditions','2006-nepal-drought-conditions',(SELECT id FROM categories WHERE slug='drought'),'2006-01-01','2006','Mid-western, far-western and Terai districts','Rainfall irregularity and dry conditions affected farming and water access in parts of Nepal in 2006.','Agricultural drought can be intensified by delayed monsoon onset, winter rainfall deficits and limited irrigation. Available reports describe localized impacts rather than one nationally uniform disaster.','No single disaster death toll','Livelihood and food-security impacts','Seasonal rainfall deficit','Crop yields, livestock, water sources and food security were affected in vulnerable areas.','DHM; FAO; Government of Nepal agricultural assessments',0,'PUBLISHED'),
('2015 Nepal Drought and Water Stress','2015-nepal-drought-and-water-stress',(SELECT id FROM categories WHERE slug='drought'),'2015-01-01','2015','Western and mid-western Nepal','Dry conditions and water stress affected some communities during the 2015 agricultural year.','Drought impacts can coexist with other disasters and are often overshadowed by sudden events. In 2015, local water availability, crop conditions and post-earthquake vulnerability varied widely by district, so this record does not assign a single national drought toll.','No single disaster death toll','Livelihood and water-security impacts','Seasonal rainfall deficit and water stress','Agriculture, livestock and household water access were affected in some districts.','DHM; FAO; Ministry of Agriculture and Livestock Development',0,'PUBLISHED'),

('2010 Terai Heat Wave','2010-terai-heat-wave',(SELECT id FROM categories WHERE slug='heat-wave'),'2010-05-01','2010','Terai plains','High temperatures in the Terai created seasonal heat stress for outdoor workers and vulnerable people.','The Terai can experience dangerous heat before the monsoon. Risk increases where shade, drinking water and healthcare are limited. Historical health reporting does not consistently separate heat-related illness from other causes, so no unsupported mortality figure is used here.','Event-specific mortality varies','Heat-related illness varies','Extreme pre-monsoon heat','Health, labor, livestock, crops and water demand were affected.','DHM; Ministry of Health and Population; WHO heat-health guidance',0,'PUBLISHED'),
('2016 Nepal Heat Wave','2016-nepal-heat-wave',(SELECT id FROM categories WHERE slug='heat-wave'),'2016-05-01','2016','Terai and southern plains','A period of extreme pre-monsoon heat affected the Terai in 2016.','Heat waves can be intensified by humidity, dense settlements, limited shade and outdoor work. This event record should be paired with station observations and health surveillance because temperatures and impacts differed between districts.','Event-specific mortality varies','Heat-related illness varies','Extreme high temperature','People, livestock, crops and water systems were exposed to heat stress.','DHM; Ministry of Health and Population; WHO heat-health guidance',0,'PUBLISHED'),
('2022 Nepal Heat Wave','2022-nepal-heat-wave',(SELECT id FROM categories WHERE slug='heat-wave'),'2022-05-01','2022','Terai plains','High temperatures and delayed monsoon conditions created heat stress across parts of the Terai in 2022.','The 2022 heat period shows why heat preparedness needs clear thresholds, public messaging and protection for outdoor workers. Official impact estimates should be preferred over social-media or media-only counts.','Event-specific mortality varies','Heat-related illness varies','Extreme high temperature','Health, labor productivity, agriculture, livestock and water demand were affected.','DHM; Ministry of Health and Population; WHO heat-health guidance',0,'PUBLISHED'),

('2003 Nepal Cold Wave','2003-nepal-cold-wave',(SELECT id FROM categories WHERE slug='cold-wave'),'2003-01-01','2003','Terai plains','Persistent winter fog and low temperatures affected vulnerable communities in the Terai during 2003.','Cold waves are often undercounted because they develop over several days and their health impacts may be recorded under broader winter illness categories. This record groups the hazard period without claiming a precise national death toll.','Event-specific mortality varies','Cold-related illness varies','Low temperature and persistent fog','Health, transport, crops, livestock and schools were affected.','DHM; Ministry of Health and Population; Government of Nepal winter reports',0,'PUBLISHED'),
('2011 Nepal Cold Wave','2011-nepal-cold-wave',(SELECT id FROM categories WHERE slug='cold-wave'),'2011-01-01','2011','Terai and southern plains','A winter cold wave affected the Terai through low temperatures, fog and disruption to daily life.','Cold-wave impacts can be severe for people without insulated housing or heating. Dense fog also reduces road and aviation visibility. District-level records are needed to separate this season from normal winter conditions.','Event-specific mortality varies','Cold-related illness varies','Low temperature and persistent fog','Health, transport, agriculture and livestock were affected.','DHM; Government of Nepal winter disaster reports',0,'PUBLISHED'),
('2023 Nepal Cold Wave','2023-nepal-cold-wave',(SELECT id FROM categories WHERE slug='cold-wave'),'2023-01-01','2023','Terai and southern plains','Cold conditions and dense fog affected transport, schools, agriculture and vulnerable people in the Terai during 2023.','The 2023 winter record highlights the need for local cold-wave warnings and protection for older adults, children, outdoor workers and people in poorly heated homes. Exact health impacts vary by district and reporting method.','Event-specific mortality varies','Cold-related illness varies','Low temperature and persistent fog','Health, transport, crops, livestock and public services were affected.','DHM; Ministry of Health and Population; Government of Nepal winter reports',0,'PUBLISHED'),

('1991 Nepal Forest Fire Season','1991-nepal-forest-fire-season',(SELECT id FROM categories WHERE slug='wildfire'),'1991-03-01','1991','Hills and Terai forests','Dry-season fires affected forests and rural land in Nepal during the early 1990s.','Forest-fire reporting was less systematic before satellite monitoring. Fires were often detected through local observation, and impacts on air quality and biodiversity were rarely measured consistently. This record should be expanded with forest district archives.','Varies by incident','Varies by incident','Dry-season wildfire activity','Forest ecosystems, wildlife, pasture and nearby farms were affected.','Department of Forests and Soil Conservation; historical district records',0,'PUBLISHED'),
('2000 Nepal Forest Fire Season','2000-nepal-forest-fire-season',(SELECT id FROM categories WHERE slug='wildfire'),'2000-03-01','2000','Hills and Terai forests','Dry vegetation and pre-monsoon conditions contributed to recurring forest fires across Nepal in 2000.','Wildfire risk increases when winter and spring rainfall is low, vegetation dries and wind spreads flames. Earlier seasons are difficult to compare because detection and reporting systems were less complete than today.','Varies by incident','Varies by incident','Dry-season wildfire activity','Forests, biodiversity, air quality and nearby settlements were exposed.','Department of Forests and Soil Conservation; FAO; historical district records',0,'PUBLISHED'),
('2010 Nepal Forest Fire Season','2010-nepal-forest-fire-season',(SELECT id FROM categories WHERE slug='wildfire'),'2010-03-01','2010','Multiple districts across Nepal','Forest fires during the 2010 dry season affected forests, smoke levels and rural communities.','The 2010 season is included as a national wildfire record because fires occurred across multiple districts. Exact burned-area estimates depend on the detection method and should be checked against satellite products and forest inventories.','Varies by incident','Varies by incident','Widespread dry-season fires','Forests, air quality, wildlife habitat and local livelihoods were affected.','Department of Forests and Soil Conservation; ICIMOD; NASA FIRMS',0,'PUBLISHED'),
('2024 Nepal Wildfire Season','2024-nepal-wildfire-season',(SELECT id FROM categories WHERE slug='wildfire'),'2024-03-01','2024','Multiple districts across Nepal','The 2024 dry season brought recurring wildfires, smoke and air-quality concerns across Nepal.','Wildfire activity before the monsoon can affect forests and communities over a wide area. Satellite fire detections show activity but do not by themselves establish burned area, cause or human loss; those details require ground verification.','Varies by incident','Varies by incident','Widespread dry-season wildfire activity','Forest ecosystems, air quality, biodiversity and nearby settlements were affected.','ICIMOD; NASA FIRMS; Department of Forests and Soil Conservation; DHM',0,'PUBLISHED'),

('1982 Nepal Debris-Flow Events','1982-nepal-debris-flow-events',(SELECT id FROM categories WHERE slug='other'),'1982-07-01','1982','Hill valleys and mountain roads','Debris flows repeatedly affected steep valleys during intense monsoon rainfall in the early 1980s.','Debris flows combine water, soil, rock and vegetation and can move faster than ordinary landslides. Historical national summaries often grouped them with floods or landslides, so this archive entry preserves the cross-category hazard without assigning unsupported totals.','Not reliably established','Not reliably established','Rainfall-triggered debris flow','River corridors, roads, bridges, homes and farmland were exposed.','Government of Nepal disaster-risk profile; Department of Water Induced Disaster Management',0,'PUBLISHED'),
('1999 Nepal Wind and Rain Disasters','1999-nepal-wind-and-rain-disasters',(SELECT id FROM categories WHERE slug='other'),'1999-07-01','1999','Multiple districts','Combined wind, intense rain and localized flooding affected communities across Nepal in 1999.','Some disaster reports record compound weather events under broad categories such as storm, flood or other disaster. This entry is retained for search and historical discovery while district-level source records are reviewed.','Incident totals vary','Incident totals vary','Compound severe-weather event','Roofs, crops, drainage systems, homes and local roads were affected.','Government of Nepal disaster-risk profile; DHM; district administration reports',0,'PUBLISHED'),
('2005 Nepal Multi-Hazard Monsoon Events','2005-nepal-multi-hazard-monsoon-events',(SELECT id FROM categories WHERE slug='other'),'2005-07-01','2005','Multiple districts','The 2005 monsoon produced a combination of floods, landslides, debris flows and severe storms.','Monsoon disaster seasons are not single hazards. Rainfall can trigger flooding in the plains, slope failure in the hills and debris flows in narrow valleys at the same time. This grouped record should be read with the individual hazard entries.','Season total varies by source','Many reported or displaced','Compound monsoon hazard','Homes, farmland, roads, bridges and local services were affected.','Government of Nepal disaster-risk profile; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2013 Nepal Multi-Hazard Monsoon Events','2013-nepal-multi-hazard-monsoon-events',(SELECT id FROM categories WHERE slug='other'),'2013-07-01','2013','Multiple districts','The 2013 monsoon produced interacting floods, landslides, lightning and severe storms across Nepal.','A national archive benefits from recording compound seasons because the same rainfall system can create different impacts in different terrain. Precise totals should be taken from annual government reporting and not inferred from this grouped story.','Season total varies by source','Many reported or displaced','Compound monsoon hazard','River flooding, slope failures, road blockages, crop losses and service disruption occurred.','Government of Nepal disaster-risk profile; DHM; NDRRMA',0,'PUBLISHED'),
('2018 Nepal Multi-Hazard Monsoon Events','2018-nepal-multi-hazard-monsoon-events',(SELECT id FROM categories WHERE slug='other'),'2018-07-01','2018','Multiple districts','Floods, landslides, lightning and severe storms occurred across Nepal during the 2018 monsoon.','The 2018 season illustrates why disaster records should link weather, terrain and exposure. Different districts experienced different combinations of hazards, and national totals changed as new incidents were reported.','Season total varies by official reporting period','Many reported or displaced','Compound monsoon hazard','Transport, settlements, agriculture, hydropower and local services were affected.','Government of Nepal/NDRRMA; DHM; Nepal Disaster Risk Reduction Portal',0,'PUBLISHED'),
('2021 Nepal Compound Disaster Season','2021-nepal-compound-disaster-season',(SELECT id FROM categories WHERE slug='other'),'2021-06-01','2021','Multiple districts','Nepal experienced earthquakes, floods, debris flows, landslides, fires and severe weather during 2021.','The 2021 archive record includes several hazard types rather than one event. Compound and consecutive disasters can stretch emergency capacity, damage the same infrastructure repeatedly and make recovery more difficult. Individual stories should remain the authoritative source for each incident.','Season total varies by hazard and source','Many reported or displaced','Multiple hazards','Housing, roads, bridges, water systems, farms and public services were affected.','Government of Nepal/NDRRMA; DHM; ICIMOD; sector assessments',0,'PUBLISHED'),
('2024 Nepal Compound Monsoon Disaster','2024-nepal-compound-monsoon-disaster',(SELECT id FROM categories WHERE slug='other'),'2024-09-27','2024','Central and eastern Nepal','Late September 2024 combined extreme rainfall, river flooding, landslides and transport disruption.','The 2024 disaster period shows how one extreme rainfall episode can affect urban valleys, hill roads and lowland rivers at the same time. Early reports were provisional; final figures should follow the consolidated Government of Nepal assessment and distinguish deaths, missing people and displaced households.','Official totals vary by assessment date','Hundreds reported in the wider disaster period','Compound extreme-rainfall event','Homes, roads, bridges, farms, schools and public infrastructure were damaged.','Government of Nepal/NDRRMA; DHM; UN and World Bank assessments',1,'PUBLISHED'),
('2024 Nepal Compound Monsoon Disaster','2024-nepal-compound-monsoon-disaster',(SELECT id FROM categories WHERE slug='other'),'2024-09-27','2024','Central and eastern Nepal','Late September 2024 combined extreme rainfall, river flooding, landslides and transport disruption.','The 2024 disaster period shows how one extreme rainfall episode can affect urban valleys, hill roads and lowland rivers at the same time. Early reports were provisional; final figures should follow the consolidated Government of Nepal assessment and distinguish deaths, missing people and displaced households.','Official totals vary by assessment date','Hundreds reported in the wider disaster period','Compound extreme-rainfall event','Homes, roads, bridges, farms, schools and public infrastructure were damaged.','Government of Nepal/NDRRMA; DHM; UN and World Bank assessments',1,'PUBLISHED');

-- Add a longer encyclopedia-style context paragraph to every published story.
UPDATE stories s
JOIN categories c ON c.id = s.category_id
SET s.content = CONCAT(s.content, '\n\n',
CASE c.slug
 WHEN 'earthquake' THEN 'Earthquakes in Nepal are associated with the ongoing collision between the Indian and Eurasian tectonic plates, which drives shortening and uplift across the Himalaya. The hazard is shaped not only by the size of an earthquake but also by depth, distance from populated places, local ground conditions, building materials and the ability of roads, hospitals and communications systems to remain operational. Historical accounts frequently use approximate dates, reconstructed magnitudes and changing administrative boundaries, while modern assessments may revise casualty and damage totals as field surveys continue. For that reason, this article should be read alongside the cited catalogue or government assessment, with estimates retained as estimates and later revisions documented rather than silently replaced.'
 WHEN 'flood' THEN 'Flood disasters in Nepal reflect the interaction of monsoon rainfall, snowmelt, steep tributaries, sediment movement, river morphology and settlement on flood-prone land. The same weather system may produce rapid flash flooding in a mountain valley, prolonged inundation in the Terai and landslides on connecting roads. Damage is often greater where bridges, embankments, homes and public services have been built in exposed corridors or where early warning cannot reach communities in time. Event totals should identify the reporting date and distinguish deaths, missing people, displaced households, affected people and economic damage.'
 WHEN 'landslide' THEN 'Landslides are common across the middle hills and mountain valleys because steep terrain, fractured rock, intense rainfall and active river erosion combine with roads, settlement expansion and changing land use. A slide may begin as a shallow failure beside a road or become a large debris flow that blocks a river and threatens communities downstream. Earthquake shaking can leave slopes unstable for years, while later monsoon rain can reactivate cracks and scarps. Reliable interpretation therefore requires attention to the date of movement, the triggering process, the size of the slide, the exposed population and the quality of the source survey.'
 WHEN 'avalanche' THEN 'Avalanche risk in Nepal is concentrated in high mountain terrain where snowfall, wind loading, rapid temperature change, serac collapse and unstable slopes can release snow and ice onto climbing routes, trails and settlements. Historical reporting is often strongest for expeditions and popular trekking corridors, while losses in remote valleys may be incompletely recorded. The apparent severity of an avalanche depends on its path, timing, depth, terrain and the number of people present, so a report should separate deaths, injuries, missing people, rescues and route closures. Expedition records, local administration reports and technical snow studies provide complementary evidence.'
 WHEN 'glof' THEN 'Glacial lake outburst floods, commonly abbreviated as GLOFs, occur when a moraine, ice dam or other natural barrier fails and releases stored lake water, sediment and ice into a downstream valley. In Nepal, lake growth is linked to glacier retreat, ice collapse, changing precipitation and the geometry of high mountain basins, although each lake has its own history and failure mechanisms. A GLOF can travel rapidly through narrow channels and damage bridges, hydropower, trails, farmland and settlements far below the lake. Inventory dates and lake names sometimes differ between publications, so event descriptions should distinguish confirmed outbursts from hazard assessments and possible future scenarios.'
 WHEN 'lightning' THEN 'Lightning is a recurring atmospheric hazard in Nepal, particularly during pre-monsoon and monsoon thunderstorms. Exposure is increased when people are working in fields, travelling on foot, gathering beneath isolated trees or using poorly protected buildings and electrical equipment. Unlike a single large disaster, the national burden is usually made up of many local incidents whose details arrive through district reporting systems at different times. A responsible historical account should therefore state whether a number is an annual total, a preliminary count or an incident-specific figure, and should give equal attention to prevention measures such as safe shelter, public warnings and school procedures.'
 WHEN 'storm' THEN 'Severe storms in Nepal may combine hail, damaging wind, lightning, intense short-duration rain and, in some places, flash flooding. Their impacts can be highly localized: a single storm cell may destroy crops and roofs in one municipality while nearby stations record much less severe weather. Agricultural losses are particularly difficult to compare because crop stage, protected cultivation, livestock exposure and access to insurance vary between communities. Weather-station observations, radar or satellite evidence, local damage surveys and government relief records should be considered together when reconstructing an event.'
 WHEN 'tornado' THEN 'Tornadoes and tornado-like rotating windstorms are uncommon in Nepal but can produce concentrated destruction over a narrow path. Classification is difficult when an event has not been observed by radar or surveyed soon after the damage, because straight-line winds, downbursts and rotating storms can leave similar local evidence. A wiki-style record should identify the reporting authority, describe the affected path and avoid treating every severe wind report as a confirmed tornado. Homes, roofs, trees, crops, electricity lines and community buildings are important indicators of impact, while casualty figures should be linked to a dated official assessment.'
 WHEN 'drought' THEN 'Drought is a slow-onset hazard caused by a sustained mismatch between available water and the needs of people, ecosystems, crops or livestock. In Nepal it may follow deficient winter rain, a delayed or weak monsoon, prolonged dry spells, reduced spring water or a combination of these conditions. The effects are often uneven: one district may experience crop failure while another has adequate irrigation or rainfall. Historical analysis should distinguish meteorological drought from agricultural, hydrological and socioeconomic drought, and should describe food security, migration, livestock, drinking-water access and household coping strategies rather than relying only on a death toll.'
 WHEN 'heat-wave' THEN 'Heat waves in Nepal are most strongly associated with the Terai and southern plains, where high temperatures can combine with humidity, limited shade, outdoor labour, dense settlements and restricted access to cooling or medical care. Heat is often undercounted because illness may be recorded as dehydration, cardiovascular stress or another condition rather than as a disaster fatality. A useful historical record should include observed temperatures, duration, affected districts, vulnerable groups and public-health measures when those data are available. Heat warnings, drinking water, shaded rest, adjusted work hours and access to treatment are central parts of risk reduction.'
 WHEN 'cold-wave' THEN 'Cold waves in the Terai are commonly accompanied by persistent fog, low daytime temperatures and reduced visibility. The hazard affects people living in poorly insulated homes, older adults, children, outdoor workers, people with chronic illness, livestock and winter crops. Transport and school attendance may also be disrupted even when no single dramatic incident is recorded. Because cold-related deaths and illness can be attributed to several medical causes, historical totals are frequently uncertain. Records should therefore explain the duration and geographic extent of the cold period and identify the source used for any health estimate.'
 WHEN 'wildfire' THEN 'Wildfires in Nepal are most frequent during the dry period before the summer monsoon, when grasses, leaf litter and forest vegetation become flammable and wind can carry fire across slopes. Ignition may be accidental, agricultural or deliberate, and a satellite hotspot does not by itself prove the size, cause or severity of a ground fire. Smoke can affect distant towns and people with respiratory conditions even when flames remain far from settlements. A detailed archive entry should separate detected fire points, burned area, forest type, damage to homes or livelihoods, injuries, deaths and the effectiveness of suppression or community response.'
 ELSE 'Natural disasters in Nepal are shaped by the country\'s extreme geographic range, from the high Himalaya through steep middle hills to the densely settled Terai. A single season may involve several hazards at once, and the consequences depend on exposure, poverty, infrastructure quality, warning coverage, governance and access to emergency services. Historical records are strongest when they clearly separate observed facts, estimates, preliminary reports and later revisions. This article should therefore be updated with dated government assessments, technical studies and local evidence while preserving the uncertainty attached to older or incomplete records.'
END)
WHERE s.status = 'PUBLISHED'
	AND CASE c.slug
		WHEN 'earthquake' THEN s.content NOT LIKE '%Earthquakes in Nepal are associated with the ongoing collision%'
		WHEN 'flood' THEN s.content NOT LIKE '%Flood disasters in Nepal reflect the interaction%'
		WHEN 'landslide' THEN s.content NOT LIKE '%Landslides are common across the middle hills%'
		WHEN 'avalanche' THEN s.content NOT LIKE '%Avalanche risk in Nepal is concentrated%'
		WHEN 'glof' THEN s.content NOT LIKE '%Glacial lake outburst floods, commonly abbreviated%'
		WHEN 'lightning' THEN s.content NOT LIKE '%Lightning is a recurring atmospheric hazard%'
		WHEN 'storm' THEN s.content NOT LIKE '%Severe storms in Nepal may combine%'
		WHEN 'tornado' THEN s.content NOT LIKE '%Tornadoes and tornado-like rotating windstorms%'
		WHEN 'drought' THEN s.content NOT LIKE '%Drought is a slow-onset hazard%'
		WHEN 'heat-wave' THEN s.content NOT LIKE '%Heat waves in Nepal are most strongly associated%'
		WHEN 'cold-wave' THEN s.content NOT LIKE '%Cold waves in the Terai are commonly accompanied%'
		WHEN 'wildfire' THEN s.content NOT LIKE '%Wildfires in Nepal are most frequent%'
		ELSE s.content NOT LIKE '%Natural disasters in Nepal are shaped by the country%'
	END;

-- End of expanded archive dataset.
