USE nepal_disaster_archive;

CREATE TABLE IF NOT EXISTS story_images (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NOT NULL, image_path VARCHAR(255) NOT NULL, caption VARCHAR(255), credit VARCHAR(255), sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE, INDEX(story_id)
);
CREATE TABLE IF NOT EXISTS story_sources (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, publisher VARCHAR(255), url VARCHAR(500), published_on DATE NULL, verified TINYINT(1) NOT NULL DEFAULT 0, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE, INDEX(story_id)
);
CREATE TABLE IF NOT EXISTS correction_reports (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NULL, name VARCHAR(120), email VARCHAR(190), message TEXT NOT NULL, status ENUM('OPEN','RESOLVED') NOT NULL DEFAULT 'OPEN', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE SET NULL, INDEX(status)
);
CREATE TABLE IF NOT EXISTS analytics_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NULL, event_type VARCHAR(40) NOT NULL, search_term VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE SET NULL, INDEX(event_type), INDEX(story_id), INDEX(created_at)
);
CREATE TABLE IF NOT EXISTS admin_activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id INT UNSIGNED NULL, action VARCHAR(80) NOT NULL, details VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(admin_id) REFERENCES admins(id) ON DELETE SET NULL, INDEX(created_at)
);