USE nepal_disaster_archive;

CREATE TABLE IF NOT EXISTS volunteers (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(190) NOT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, emergency_contact_name VARCHAR(190), emergency_contact_phone VARCHAR(50), volunteer_type VARCHAR(80) NOT NULL, location VARCHAR(255) NOT NULL, availability ENUM('AVAILABLE','ON_CALL','UNAVAILABLE') NOT NULL DEFAULT 'ON_CALL', skills TEXT, role_details TEXT, languages VARCHAR(255), blood_type VARCHAR(5), last_donation_date DATE NULL, consent_confirmed TINYINT(1) NOT NULL DEFAULT 0, status ENUM('PENDING','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'PENDING', reviewed_by INT UNSIGNED NULL, reviewed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(reviewed_by) REFERENCES admins(id) ON DELETE SET NULL, INDEX(volunteer_type), INDEX(location), INDEX(availability), INDEX(status)
);
CREATE TABLE IF NOT EXISTS emergency_contacts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, service VARCHAR(80) NOT NULL, organization VARCHAR(190) NOT NULL, title VARCHAR(190) NOT NULL, phone VARCHAR(255) NOT NULL, province VARCHAR(120), district VARCHAR(120), municipality VARCHAR(190), address VARCHAR(255), coverage TEXT, availability_note TEXT, verification_status ENUM('OFFICIAL','LOCAL_VERIFIED','NEEDS_VERIFICATION','REPORTED_INACTIVE') NOT NULL DEFAULT 'NEEDS_VERIFICATION', last_verified DATE NULL, source_url VARCHAR(500), notes TEXT, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(service), INDEX(province), INDEX(district), INDEX(active), INDEX(verification_status)
);

ALTER TABLE stories
  ADD COLUMN story_type ENUM('DISASTER','HUMAN') NOT NULL DEFAULT 'DISASTER' AFTER category_id,
  ADD COLUMN storyteller_name VARCHAR(190) NULL AFTER impact,
  ADD COLUMN storyteller_role VARCHAR(120) NULL AFTER storyteller_name,
  ADD COLUMN consent_note TEXT NULL AFTER storyteller_role;

ALTER TABLE stories
  MODIFY COLUMN status ENUM('DRAFT','REVIEW','PUBLISHED') NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN district VARCHAR(120) NULL AFTER location,
  ADD COLUMN province VARCHAR(120) NULL AFTER district,
  ADD COLUMN latitude DECIMAL(10,7) NULL AFTER province,
  ADD COLUMN longitude DECIMAL(10,7) NULL AFTER latitude,
  ADD COLUMN image_path VARCHAR(255) NULL AFTER longitude,
  ADD COLUMN reviewed_at DATETIME NULL AFTER status,
  ADD COLUMN reviewed_by INT UNSIGNED NULL AFTER reviewed_at;

CREATE TABLE IF NOT EXISTS story_revisions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 story_id INT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL,
 content LONGTEXT NOT NULL,
 saved_by INT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE,
 FOREIGN KEY(saved_by) REFERENCES admins(id) ON DELETE SET NULL,
 INDEX(story_id)
);