USE nepal_disaster_archive;

ALTER TABLE stories
  MODIFY COLUMN status ENUM('DRAFT','REVIEW','PUBLISHED') NOT NULL DEFAULT 'DRAFT',
  ADD COLUMN district VARCHAR(120) NULL AFTER location,
  ADD COLUMN province VARCHAR(120) NULL AFTER district,
  ADD COLUMN latitude DECIMAL(10,7) NULL AFTER province,
  ADD COLUMN longitude DECIMAL(10,7) NULL AFTER latitude,
  ADD COLUMN image_path VARCHAR(255) NULL AFTER longitude,
  ADD COLUMN reviewed_at DATETIME NULL AFTER status,
  ADD COLUMN reviewed_by INT UNSIGNED NULL AFTER reviewed_at;

CREATE TABLE IF NOT EXISTS story_revisions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 story_id INT UNSIGNED NOT NULL,
 title VARCHAR(255) NOT NULL,
 content LONGTEXT NOT NULL,
 saved_by INT UNSIGNED NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE,
 FOREIGN KEY(saved_by) REFERENCES admins(id) ON DELETE SET NULL,
 INDEX(story_id)
);