USE nepal_disaster_archive;

ALTER TABLE stories ADD COLUMN story_type ENUM('DISASTER','HUMAN') NOT NULL DEFAULT 'DISASTER' AFTER category_id;
ALTER TABLE stories ADD COLUMN storyteller_name VARCHAR(190) NULL AFTER impact;
ALTER TABLE stories ADD COLUMN storyteller_role VARCHAR(120) NULL AFTER storyteller_name;
ALTER TABLE stories ADD COLUMN consent_note TEXT NULL AFTER storyteller_role;

CREATE TABLE IF NOT EXISTS story_images (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NOT NULL, image_path VARCHAR(255) NOT NULL, caption VARCHAR(255), credit VARCHAR(255), sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE, INDEX(story_id)
);
CREATE TABLE IF NOT EXISTS story_sources (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NOT NULL, title VARCHAR(255) NOT NULL, publisher VARCHAR(255), url VARCHAR(500), published_on DATE NULL, verified TINYINT(1) NOT NULL DEFAULT 0, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE CASCADE, INDEX(story_id)
);
CREATE TABLE IF NOT EXISTS correction_reports (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NULL, name VARCHAR(120), email VARCHAR(190), message TEXT NOT NULL, status ENUM('OPEN','RESOLVED') NOT NULL DEFAULT 'OPEN', created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE SET NULL, INDEX(status)
);
CREATE TABLE IF NOT EXISTS story_submissions (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, title VARCHAR(255) NOT NULL, storyteller_name VARCHAR(190), storyteller_role VARCHAR(120), email VARCHAR(190), location VARCHAR(255), event_date DATE NULL, story_content LONGTEXT NOT NULL, image_path VARCHAR(255), is_anonymous TINYINT(1) NOT NULL DEFAULT 0, consent_confirmed TINYINT(1) NOT NULL DEFAULT 0, status ENUM('SUBMITTED','APPROVED','REJECTED') NOT NULL DEFAULT 'SUBMITTED', reviewed_by INT UNSIGNED NULL, reviewed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(reviewed_by) REFERENCES admins(id) ON DELETE SET NULL, INDEX(status), INDEX(created_at)
);
CREATE TABLE IF NOT EXISTS volunteers (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, full_name VARCHAR(190) NOT NULL, email VARCHAR(190) NOT NULL, phone VARCHAR(50) NOT NULL, emergency_contact_name VARCHAR(190), emergency_contact_phone VARCHAR(50), volunteer_type VARCHAR(80) NOT NULL, location VARCHAR(255) NOT NULL, availability ENUM('AVAILABLE','ON_CALL','UNAVAILABLE') NOT NULL DEFAULT 'ON_CALL', skills TEXT, role_details TEXT, languages VARCHAR(255), blood_type VARCHAR(5), last_donation_date DATE NULL, consent_confirmed TINYINT(1) NOT NULL DEFAULT 0, status ENUM('PENDING','ACTIVE','INACTIVE','ARCHIVED') NOT NULL DEFAULT 'PENDING', reviewed_by INT UNSIGNED NULL, reviewed_at DATETIME NULL, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, FOREIGN KEY(reviewed_by) REFERENCES admins(id) ON DELETE SET NULL, INDEX(volunteer_type), INDEX(location), INDEX(availability), INDEX(status)
);
CREATE TABLE IF NOT EXISTS emergency_contacts (
 id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY, service VARCHAR(80) NOT NULL, organization VARCHAR(190) NOT NULL, title VARCHAR(190) NOT NULL, phone VARCHAR(255) NOT NULL, province VARCHAR(120), district VARCHAR(120), municipality VARCHAR(190), address VARCHAR(255), coverage TEXT, availability_note TEXT, verification_status ENUM('OFFICIAL','LOCAL_VERIFIED','NEEDS_VERIFICATION','REPORTED_INACTIVE') NOT NULL DEFAULT 'NEEDS_VERIFICATION', last_verified DATE NULL, source_url VARCHAR(500), notes TEXT, active TINYINT(1) NOT NULL DEFAULT 1, created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, INDEX(service), INDEX(province), INDEX(district), INDEX(active), INDEX(verification_status)
);
CREATE TABLE IF NOT EXISTS analytics_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, story_id INT UNSIGNED NULL, event_type VARCHAR(40) NOT NULL, search_term VARCHAR(255), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(story_id) REFERENCES stories(id) ON DELETE SET NULL, INDEX(event_type), INDEX(story_id), INDEX(created_at)
);
CREATE TABLE IF NOT EXISTS admin_activity (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY, admin_id INT UNSIGNED NULL, action VARCHAR(80) NOT NULL, details VARCHAR(500), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(admin_id) REFERENCES admins(id) ON DELETE SET NULL, INDEX(created_at)
);